cornell-dti/office-hours

package-lock.json, public/index.html
=> Change title

package-lock.json, package.json, src/App.tsx, src/SessionInformationHeader.css, src/SessionInformationHeader.tsx, src/SessionPopularQuestionsContainer.css, src/SessionPopularQuestionsContainer.tsx, src/SessionQuestionsContainer.css, src/SessionQuestionsContainer.tsx, src/StudentSessionView.css, src/StudentSessionView.tsx
Changed App to display StudentSessionView, which in turn contains 3 high-level components for now:
- SessionInformationHeader
- SessionPopularQuestionsContainer
- SessionQuestionsContainer
These skeletons will be populated in a future PR
=> Setting up StudentSessionView skeleton

client/src/components/includes/CalendarHeader.tsx, client/src/components/pages/CalendarView.tsx, client/src/styles/CalendarHeader.css
Reverts cornell-dti/office-hours#16
Need to push my code first before merging in new stuff
=> Revert "Branch updates"

client/package-lock.json, client/package.json, client/src/components/includes/CalendarSessionCard.tsx, client/src/components/includes/CalendarSessions.tsx, client/src/styles/CalendarHeader.css, client/src/styles/CalendarSessions.css
Some issues:
* It looks like I'll need to include some Javascript to convert unix times to regular times, but I'm not sure how to include that code in the .tsx file
* I couldn't get the SessionIndicator (the red/white circles) to highlight only for the first session. Though eventually they'll be highlighted based on if the OH is occuring right now.
* It looks like the line lengths are based on how long the OH is. I'm not sure how to dynamically change the CSS based on that.
* The dots and lines are centered manuallly since I couldn't find a way to center elements in different dividers.
=> Add first version of Calendar Sessions

client/package-lock.json, client/package.json, client/src/components/App.tsx
- Installed `react-router-dom`
- Separated Calendar and Student Session views to their own routes
- Added navigation at the top for convenience
=> Setting up react-router

client/src/components/includes/CalendarDateSelect.tsx, client/src/components/includes/CalendarWeekSelect.tsx, client/src/components/pages/CalendarView.tsx, client/src/styles/CalendarHeader.css, client/src/styles/CalendarWeekSelect.css
- Added state (`currentEpoch`) to CalendarView
- State changes with week selector clicks
- Date select responds to state changes
=> Completing Calendar Week Control

client/src/components/includes/CalendarDateSelect.tsx, client/src/components/includes/CalendarSessions.tsx, client/src/components/pages/CalendarView.tsx
- Added `selectedDateEpoch` to the CalendarView state
- Lifting selected date state from CalendarDateSelect to CalendarView
- Added `todayEpoch` to CalendarSessions, which can now be used to query the database
=> Selected date state in CalendarView

client/src/components/includes/DetailedQuestionView.tsx, client/src/components/includes/SessionPopularQuestion.tsx, client/src/components/includes/SessionPopularQuestionsContainer.tsx, client/src/components/includes/SessionQuestionsComponent.tsx, client/src/components/includes/SessionQuestionsContainer.tsx, client/src/components/pages/StudentSessionView.tsx, client/src/styles/DetailedQuestionView.css, client/src/styles/StudentSessionView.css
- The background stops scrolling when the pop-up is visible, but the scroll position jumps up to the top.
- I'm passing down the toggle function to each subcomponent using prop; let me know if there's a better way to do this.
- I'm also running into a minor issue where some CSS styles are unintentionally applied to other HTML files, such as if class names are the same, or if I'm styling general elements like buttons. I can get around this by using unique class names, but is there a way to make a CSS file specific to one .tsx file?
- How should information from a question card be passed to the pop-up?
=> Detailed Question View (initial)

server/index.ts
- Uncommented PostgraphQL
- Added `__` to the front of gql routes
- Fix deep linking
=> Fixing PostgraphQL routes

client/src/components/includes/CalendarSessions.tsx, server/office_hours.sql
Fix mock data and sort sessions by startTime in React
=> Data fixes ahead of demo

client/src/components/includes/CalendarSessions.tsx, client/src/components/includes/SessionInformationHeader.tsx, docs/database.md, server/index.ts, server/office_hours.sql
- Adding detailed documentation for the database schema and functions in `/docs`
- Redoing PL/pgSQL functions to make them cleaner, consistent, and to separate API and internal functions. Created API functions to manipulate sessions and session series.
- Redid mock data to comply with the documentation/constraints
=> Database Documentation

client/src/components/includes/SessionInformationHeader.tsx
Prevent crash when trying to get ta picture for sessions when there are no TAs
=> Hotfix: Handle 0 Tas

client/src/components/includes/SessionView.tsx
Temporarily lower request interval, p95 hit almost 8s not at 5.3s.
* AAAAHHHHHH!!!!!
=> Temporarily lower request interval

client/src/components/includes/SessionView.tsx
Now that performance has stabilized, we're cutting polling interval in half down to 15 seconds.
=> Half polling interval

PULL_REQUEST_TEMPLATE.md, client/package.json, client/tsconfig.json, client/tsconfig.prod.json
* Ignore circular dependency between @types/react and @types/prop-types (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28881)
* Simplify the PR template
* Update many dependancies 
We had to add a temporary workaround where TS ignores our dependancies (which is super dangerous long term) but at least our builds will compile for now. If some time passes and this bug isn't fixed, I might try to make a PR somewhere.
=> Fix broken builds

client/src/components/includes/CalendarWeekSelect.tsx, client/src/styles/calendar/CalendarWeekSelect.less
Updates the week selector (in the professor view) to the larger redesign.
* Week selector redesign
=> Update week selector to new redesign

client/src/styles/professor/ProfessorTagInfo.less
* fixed the length and padding of the tags if the input is long.
=> fixed long tags

client/src/components/includes/TopBar.tsx, client/src/styles/TopBar.less, client/src/styles/login/LoginButton.less
* Hover state animation for the "Sign In with Google" button
* Hover state animation for the Name/Profile Picture in the top bar
The designers may want to change the colors and shadow I used for the "Sign In with Google" button's hover animation.
=> Hover name/picture and Sign In button

client/src/components/includes/AddQuestion.tsx
* When the Join the Queue view is open, Cmd/Ctrl + Enter performs the same function as clicking "Add My Question".
* When the Join the Queue view is open, Esc exits the view.
* The shortcuts only work when the cursor is in the Question textbox.
=> Cmd/Ctrl + Enter, Esc Shortcuts

client/src/components/includes/CalendarSessionCard.tsx, client/src/components/includes/CalendarSessions.tsx, client/src/components/includes/CalendarView.tsx, client/src/components/includes/SessionInformationHeader.tsx, client/src/components/includes/SessionView.tsx, client/tslint.json
* Displays the number of questions ahead of the current user's question
* If the user is not in the queue, then displays the total number of questions (as before)
=> Change Number in Queue to Number Ahead

client/src/components/includes/SessionQuestion.tsx, client/src/styles/session/SessionQuestionsComponent.less
* Implemented mobile view for the location tooltip
* Same functionality as desktop view, except view is closed with "Done" button
=> Implement Mobile Location Tooltip

client/src/components/includes/SessionView.tsx, client/src/components/types/appData.d.ts
Bug Fix: Retract prevents adding a question in another queue
* Filter questions to only count unresolved ones
=> Bug Fix: Retract prevents adding a question in another queue

client/src/components/includes/SessionQuestionsContainer.tsx
Add Queue Length to TA titlebar
* That's the only thing
=> Add Queue Length to TA titlebar

.vscode/settings.json, client/src/components/App.tsx, client/src/components/includes/CalendarHeader.tsx
* Used localStorage to remember the last Course ID a user was on
* Directs user to the most recent course that was selected
* Implemented this feature through App.tsx and CalendarHeader.tsx
* Defaulting to Course ID of 2 when most recent Course ID is null
=> Remembering Most Recent Course ID

client/src/components/includes/CalendarHeader.tsx, client/src/components/pages/LoginView.tsx, client/src/media/QLogo2.svg, client/src/styles/login/LoginButton.less, client/src/styles/login/LoginView.less, package.json
Replace logo in CalendarHeader and LoginView with new one. Also make some LoginView tweaks to bring it closer to the current design.
* Replace CalendarHeader Logo
* Replace LoginView Logo
* Change gradient on LoginView and make it the same on mobile
* Increase login button font weight and letter spacing
* Remove yarn build from the root package.json (to fix heroku builds)
* Update slogan on LoginView
Nothing serious.
=> Update Logo and LoginView

client/src/components/includes/SessionQuestion.tsx, client/src/styles/session/SessionQuestionsComponent.less
* This PR is about the new button that I added titled 'I Really Don't Know'.
* It allows TAs to un-assign themselves from a question that they do not know how to answer.
The CSS for this button is slightly different from the design in Zeplin but it is very close and very minor.
=> Added a button called 'I Really Don't Know' to allow TAs to un-assign themselves from a question.

client/src/components/pages/LoginView.tsx, client/src/styles/login/LoginView.less, client/src/styles/system.less
Provides a Contact Us info box on the login page for users interested in Queue Me In for their class.
* (From Zeplin) The “Contact Us” button opens up the user’s email application so they can contact us at  queuemein@gmail.com with the subject line "Queue Me In For Students"
* Displaying the DTI logo in the lower right corner is not yet implemented
=> Contact Us Info

client/src/components/includes/AddQuestion.tsx, client/src/components/includes/SessionAlertModal.tsx, client/src/components/includes/SessionView.tsx, client/src/components/pages/SplitView.tsx, client/src/components/types/appData.d.ts, client/src/styles/SplitView.less, client/src/styles/calendar/CalendarSessions.less, client/src/styles/session/SessionAlertModal.less, package.json
* If a student's question was marked as "no show," a notification will tell the student that they're no longer on the queue.
* Popup can also be dismissed upon refreshing
=> Show Popup If Student Is Marked As "No Show"

docs/database.md
* Added an alternative format for the psql command in case the console throws an error
=> Add psql command error fix

client/src/components/App.tsx
* Changed default courseId (when a user hasn't visited QMI before) from 2 (which was Fall 2018) to 5 (Fall 2019), which is stored as DEFAULT_COURSE_ID
* If a course is not active (its end date has passed), then redirect user to DEFAULT_COURSE_ID
=> Redirect inactive courses

PULL_REQUEST_TEMPLATE.md
=> Propose PR template change

.github/workflows/ci-workflow.yml, .gitignore, client/src/components/types/appData.d.ts, server/tslint.json
Setup GitHub Actions CI. See the check run box below.
None
=> Setup GitHub Actions CI

client/src/components/includes/AddQuestion.tsx, client/src/styles/session/AddQuestion.less
Fixes a minor styling issue
* Added padding under the add question button
=> Button Whitespace Fix

client/src/components/includes/AddQuestion.tsx, client/src/styles/session/AddQuestion.less
Reverts cornell-dti/office-hours#144
=> Revert "Button Whitespace Fix"

README.md
=> Update README with 2019-2020 roster

.vscode/settings.json, server/index.ts
* Disable PassportJS's hostedDomain check to allow a review of QueueMeIn on staging.
* NOTE: DO NOT deploy staging to production until this PR is undone. Doing so would allow non-Cornell.edu accounts to access QueueMeIn.
* Only test on queue-me-in staging.
=> Disable cornell.edu check temporarily

client/src/components/App.tsx, client/src/components/pages/LoginView.tsx, client/src/firebasefunctions.ts, client/src/firehooks.ts
* Upload User's first name, last name, account creation time, photo url, email, and last time signed in onto users/(current user uid)/ in the firebase collection.
* This occurs every time that a user either signs in manually with the popup or automatically by Google.
* Only test on queue-me-in staging.
* When a user is automatically signed in by Google (and they never have to click on their account in the popup window), their last sign in is still considered to be whenever they last used the popup window.  If this time were to be changed to account every single time that they were logged in, it would require switching the time format in the database (which is not hard).
=> Firebase Collection Update Upon Log In

.vscode/settings.json, server/index.ts
This reverts commit ac83e1b008ef4707fdd4c6a4fef30e093c0064c7.
Things work before that commit.
=> Revert "Disable cornell.edu check temporarily (#152)"

client/src/components/includes/AddQuestion.tsx, client/src/components/types/fireData.d.ts
This fixes the front end for AddQuestion View. I remove the last of the Apollo/GraphQL code and switch it for some firebase code. 
* Simply logic heavily.
* Rip out GraphQL
* Fetch data from firestore
Manual QA
There's more work to be done to simplify this file but that can be a part of a later PR.
I'm happy that we're removing a bunch of convoluted stuff but there's a lot farther to go. 
The backend is not implemented in the slightest. We're definitely going to need a cloud function for mutations because I spent a significant amount of time looking into security policies to allow direct writes, but they aren't powerful enough or expressive enough.
The TS ignore is for some reason thinking a value could be null despite checking for it in a ternary before using it. Not sure what's going on …
=> Fix front end for AddQuestion View

client/src/components/includes/ProfessorRolesTable.tsx, client/src/components/pages/ProfessorRoles.tsx, client/src/components/types/fireData.d.ts, client/src/styles/professor/ProfessorRoles.less
Implement reads for firebase manage roles screen.
* Basically reimplement the data logic for Firebase
Manually verified changes
* Weird thing with RxJS imports:
// Importing combineLatest from rxjs/operators broke everything...
import { combineLatest } from 'rxjs';
=> Firebase Reads for Professor Manage Roles Screen

client/src/components/includes/ProfessorTagInfo.tsx, client/src/components/types/fireData.d.ts
Add a type for session series
Swap remaining types from storing ID's as strings to using DocumentReferences for added safety.
* See above
N/A
=> SessionSeries type and use DocumentReferences for the types I haven't updated

client/src/components/App.tsx
Get the courseUser value before we show info to professors
* That's all, folks
Manually verified changes
Might be cool to pass the courseUser we get here as a prop into profviews to eliminate duplicate data (if we use that somewhere).
=> Protect professor routes on firebase

client/src/components/includes/AddQuestion.tsx, client/src/components/includes/CalendarSessions.tsx, client/src/components/includes/SessionQuestion.tsx, client/src/components/includes/SessionQuestionsContainer.tsx, client/src/components/includes/SessionView.tsx, client/src/firehooks.ts
* Added mutations to add a question to the Queue.
Manual QA.
=> Add question mutation

client/package.json, client/src/components/includes/QuestionsBarChart.tsx, client/src/components/includes/QuestionsLineChart.tsx, client/src/components/includes/QuestionsPieChart.tsx, client/src/components/includes/TagsBarChart.tsx, client/src/components/pages/ProfessorPeopleView.tsx, client/tsconfig.json
Modernize People View for firebase and make some other code quality improvements.
* Update Nivo to latest
* Enable ES2019 syntax
* Replace People View logic to simplify code and switch backend to Firebase
* Simplify a portion of the graph code
Manual Q&A
We need to ask product people to reconsider at how we want to handle TA's in people view. 
The existing setup assumed a 1:1 mapping from TAs to Sessions and was incapable of showing more. I believe we support up to 5 TAs per shift and none of our classes are assigning anything. I think we should push this down the road for after migration but open to other ideas.
------------
Ideally, at some point in the future we'll simplify the graph components and turn them into pure functions, but that's not a priority now since everything seems to …
=> Modernize People View

client/src/components/includes/AddQuestion.tsx, client/src/components/includes/SessionQuestionsContainer.tsx, client/src/components/includes/SessionView.tsx
=> No duplicate questions

README.md, client/src/components/includes/ProfessorOHInfoDelete.tsx, client/src/components/includes/ProfessorSettings.tsx, client/src/components/pages/ProfessorView.tsx, client/src/styles/index.less, client/src/styles/login/LoginView.less, client/src/styles/professor/ProfessorDelete.less, client/src/styles/professor/ProfessorSettings.less, client/src/styles/professor/ProfessorView.less, docs/database.md, server/database/migrations/0008_api_update_course_settings.sql
Restores some features that were accidentally lost in a previous merge.
* Restore the Login View CSS for the "Interested in using..." button
* Update list of QMI members from Fall 2019
* Restore the Professor Settings feature: https://github.com/cornell-dti/office-hours/pull/157
* Some features were accidentally lost from https://github.com/cornell-dti/office-hours/pull/158; there may be other features that need to be re-added that aren't included in this PR
=> Restore Features

docs/environment_variables.md
Added new documentation for postgress credentials.
* add new documentation for postgress credentials
=> Add postgres login credentials to documentation for .env

client/package.json, client/src/components/App.tsx, client/src/components/includes/AddQuestion.tsx, client/src/components/includes/CalendarHeader.tsx, client/src/components/includes/CalendarSessionCard.tsx, client/src/components/includes/CalendarView.tsx, client/src/components/includes/ProfessorCalendarTable.tsx, client/src/components/includes/TopBar.tsx, client/src/components/pages/LoginView.tsx, client/src/components/pages/ProfessorPeopleView.tsx, client/src/components/pages/ProfessorTagsView.tsx, client/src/firebasefunctions.ts, client/yarn.lock
Goal: reduce warnings printed in terminal.
1. Mostly applying suggestions by eslint.
2. Import `firebase/app` instead of `firebase` to follow firebase's warning in console.
3. Add `"eslintConfig": { "extends": "react-app"  }` to package.json. If you use VSCode with eslint setup, it will show these warnings directly in your editor.
No behavior change. Everything seems to work.
=> Linter fixes and getting rid of firebase warnings

client/src/components/includes/ProfessorRolesTable.tsx
Support changing the course user roles in the professor's manage user view.
1. Added the id of the course user document to the `enrichedFireCourseUser` object.
2. Use the id of the course user to perform role change update
3. Removed RYAN_TODO for loading and error. With firebase, it should be handled by the parent component, and the dropdown component should just follow its props.
This diff does come with a but: The functionality does not completely work, most likely because the security rules are not properly setup. I strongly suspect that it's caused by firebase's poor and undocumented support for references in security rules. I might experimenting changing all references to strings in a future diff.
However, the stuff does work if I disable the security rules or changing the type of …
=> Support changing course user roles

docs/database.md
Add small but important line to local Postgres server setup documentation
* added small but important line to local Postgres server setup documentation
=> update local database documentation

.github/workflows/ci-workflow.yml, client/package.json
The goal is to eventually migrate all tslint config to eslint
=> Run both eslint and tslint in CI

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/policies.yml, .gitignore, client/firebase.json, client/package.json, client/yarn.lock
Separate existing workflows into 3 files.
- policies that check for big diffs are always triggered during PR
- ci is already triggered for every push
- cd is triggered when push to develop-firebase (It will be modified to trigger on push to master once firebase branch goes into master)
=> Setup continuous deployment for firebase branch

client/src/components/includes/CalendarHeader.tsx, client/src/firehooks.ts, client/src/utilities/singleton-observable-hook.ts
Cache some commonly used values so that we can avoid refetching them again and again.
See `client/src/utilities/singleton-observable-hook.ts` for more context.
=> Setup infra for global cache and subscription, and cache enrolled courses

client/src/components/includes/Analytics.tsx, client/src/components/includes/CalendarSessions.tsx, client/src/components/includes/ProfessorCalendarTable.tsx, client/src/components/includes/ProfessorTagsTable.tsx, client/src/components/pages/ProfessorDashboardView.tsx, client/src/firehooks.ts
- Create and use a safer `useQuery` hook.
- Replace most usages of `componentWillReceiveProps` with `componentDidUpdate`
=> Fix linter warnings

client/src/components/includes/ProfessorOHInfo.tsx, client/src/components/includes/ProfessorOHInfoDelete.tsx, client/src/components/pages/ProfessorView.tsx, client/src/firebasefunctions.ts, client/src/utilities/date.ts
Added back support for professors to (create | update | delete) (sessions & series).
Security is not enforced yet.
=> Fully functional CRUD for sessions and series

client/src/components/includes/CalendarDaySelect.tsx, client/src/components/includes/CalendarHeader.tsx, client/src/components/includes/CalendarSessionCard.tsx, client/src/components/includes/CalendarWeekSelect.tsx, client/src/components/includes/Popup.tsx, client/src/components/includes/SessionInformationHeader.tsx, client/src/components/pages/LoginView.tsx
=> Use import syntax to include icons svg

client/src/components/includes/ProfessorRolesTable.tsx
=> Implement a functional but poorly designed import TA functionality

client/src/components/App.tsx, client/src/components/includes/CalendarWeekSelect.tsx, client/src/components/includes/ProfessorRolesTable.tsx, client/src/components/pages/LoginView.tsx
Bring linter warnings down to 10
*
=> Various linter fixes

client/src/components/includes/ProfessorSettings.tsx, client/src/components/pages/ProfessorView.tsx
=> Make professor settings view reachable and functional

client/src/components/includes/SessionAlertModal.tsx, client/src/components/includes/SessionView.tsx, client/src/components/types/fireData.d.ts
Previously, the view is broken because:
- Database records are broken
- Some master code has not been fully migrated
- Some firestore types are broken
Fix all above-mentioned problems
=> Make session view read work again

PULL_REQUEST_TEMPLATE.md
=> Update PR template for firebase branch

client/src/components/pages/ProfessorPeopleView.tsx
- Unbreak the queries
- Unbreak rendering when the `busiestSessionInfo` is undefined.
=> Unbreak `ProfessorPeopleView`

client/src/components/includes/QuestionsLineChart.tsx, client/src/components/includes/QuestionsPieChart.tsx, client/src/components/includes/TagsBarChart.tsx
=> Eradicate all setState warnings in chart components

client/.eslintrc.json, client/src/components/includes/QuestionsBarChart.tsx, client/src/components/includes/TagsBarChart.tsx
* Remove last two usages of `hasOwnProperty`
* Turn some linter warnings into errors, since they no longer appear in the codebase.
=> Strictify linter config

client/src/components/includes/ProfessorTagInfo.tsx
=> Tested Professor Create Tags/Assignments

client/src/components/includes/AddQuestion.tsx, client/src/components/includes/ProfessorTagInfo.tsx, client/src/components/includes/ProfessorTagsTable.tsx, client/src/components/pages/ProfessorDashboardView.tsx, client/src/components/types/fireData.d.ts
* Updated references to be strings
=> Update FireTag type

client/src/components/includes/ProfessorTagInfo.tsx, client/src/components/includes/ProfessorTagsTable.tsx
* Added a clear state so info isn't loaded after firebase query
* This fix is according to Scott, the TPM
=> Added clear state method

client/src/components/includes/AddQuestion.tsx, client/src/components/includes/CalendarView.tsx, client/src/components/includes/CourseSelection.tsx, client/src/components/includes/SessionQuestion.tsx, client/src/components/includes/SessionView.tsx
* Allows for students to view office hour sessions as well as adding/removing questions from the queue
* Does not implement undo features or TA actions (coming in another PR)
* Comments out the "show absent" modal since it's buggy with Firebase queries
=> Add Question

client/src/components/includes/SessionQuestion.tsx, client/src/components/includes/SessionView.tsx
=> Fix some linter warnings

client/src/components/includes/SessionView.tsx
In order to take advantage of the firebase hooks infra
=> Hookify Session View

client/src/components/includes/SessionQuestionsContainer.tsx
In order to take advantage of the firebase hooks infra
=> Hookify SessionQuestionsContainer

client/src/components/pages/ProfessorPeopleView.tsx
=> Compute TA names in `ProfessorPeopleView`

client/src/components/includes/CourseSelection.tsx, client/src/styles/courses/CourseSelection.less
=> Allow switch between courses edit and home mode

client/src/components/App.tsx
=> Redirect to onboarding if user has no courses

client/src/components/App.tsx
=> Fix routing to handle auto redirect when course is not found

client/src/components/includes/SessionAlertModal.tsx
=> Hookify SessionAlertModal

client/src/components/App.tsx, client/src/components/includes/SessionAlertModal.tsx
=> Display TA names in `SessionAlertModel`

client/src/components/App.tsx, client/src/components/includes/CalendarSessionCard.tsx, client/src/components/includes/CalendarSessions.tsx, client/src/components/includes/CalendarView.tsx, client/src/components/includes/CourseSelection.tsx, client/src/components/includes/SessionInformationHeader.tsx, client/src/components/pages/SplitView.tsx, client/src/firehooks.ts, client/src/utilities/singleton-observable-hook.ts
Use memoized singleton observer to avoid query question list multiple times. Thus, hooks usages on multiple components are IO efficient.
=> Correctly and efficiently compute question statistics

client/src/components/includes/CalendarSessionCard.tsx, client/src/components/includes/ProfessorOHInfoDelete.tsx, client/src/components/includes/SessionAlertModal.tsx, client/src/components/includes/SessionInformationHeader.tsx, client/src/firehooks.ts
Except `ProfessorOHInfoDelete` which needs to be hookified first.
=> Correctly render all TA Lists

client/src/components/includes/ProfessorOHInfoDelete.tsx, client/src/components/pages/ProfessorDashboardView.tsx, client/src/components/pages/ProfessorView.tsx
Number of `RYAN_TODO` is now down to 3
=> Resolve a bunch of RYAN_TODO

client/src/components/includes/AddQuestion.tsx, client/src/components/includes/ProfessorTagInfo.tsx, client/src/components/includes/SessionQuestion.tsx, client/src/components/pages/SplitView.tsx
=> Fix minor linter errors

client/src/components/App.tsx, client/src/components/pages/ProfessorDashboardView.tsx, client/src/components/pages/ProfessorPeopleView.tsx, client/src/components/pages/ProfessorRoles.tsx, client/src/components/pages/ProfessorTagsView.tsx, client/src/components/pages/ProfessorView.tsx
=> Strictify react-router types a little bit

client/src/components/includes/AddQuestion.tsx
=> Strictify type definition in `AddQuestion` and fix `@ts-ignore`

client/src/components/pages/ProfessorDashboardView.tsx, client/src/components/pages/ProfessorPeopleView.tsx
- Dashboard view: incorrect query. Do not search by documentreference
- People view: forget to multiply by 100 for percentage answered and unresolved
*
=> Unbreak professor dashboard and people view

client/src/components/includes/SessionQuestion.tsx
=> Implement `I Really Don't Know`

client/src/components/includes/ProfessorCalendarTable.tsx
=> Unbreak classification of session day in professor view

client/src/components/includes/CourseSelection.tsx
=> Make enrollment page stick to design

client/.eslintrc.json, client/src/components/includes/CourseSelection.tsx, client/src/components/includes/SessionView.tsx, client/src/components/includes/registerServiceWorker.ts, client/src/firebasefunctions.ts
=> Ban all console.log usage

client/src/components/includes/QuestionsBarChart.tsx
=> Strictify types in `QuestionsBarChart`

client/src/components/includes/CourseCard.tsx, client/src/components/includes/CourseSelection.tsx, client/src/components/includes/TopBar.tsx, client/src/styles/calendar/CalendarHeader.less
Replace `window.location.href = ...` with `history.push(...)` provided by react-router.
Therefore, we can avoid a page reload and make everything smoother.
=> Smoother route transition

.github/workflows/ci.yml
TypeScript is good. Run it in CI.
The new step passes.
=> Including running type checker `tsc` in CI

src/components/App.tsx
When the only course you enrolled in is expired, it will try to redirect to default course. If you are not in that course or the course is invalid, it will redirect to the same page again, causing an infinite redirect that breaks the site.
This diff make it redirect to the edit page instead.
1. Make yourself ONLY enrolled in the expired INFO4998.
2. Open the page, it will redirect you to edit.
After this diff is merged, let's change INFO4998's end date to June.
=> Fix the problem of infinite redirect

src/components/includes/ProfessorRolesTable.tsx, src/components/pages/AdminView.tsx, src/firebasefunctions.ts, src/styles/AdminView.less
Support managing professors and TAs in admin view by reusing `ProfessorRoleTable`.
To implement this cleanly, I have to first factor out the existing code in `ProfessorRoleTable` into `firebasefunctions.ts`.
Go to `/admin`, create a new course, and try to import professors and TAs.
=> Support managing professors and TAs in admin view

.firebaserc, .github/workflows/release.yml, package.json, src/firebase.ts
Setup a release workflow that deploys code to production firebase project, using the production site config.
Also setup a release branch. Things need to be merged into that branch to be automatically deployed. Merging to that branch requires 3 approving reviews.
Run `yarn deploy`. Install `serve` by `yarn global add serve`. Run `serve build`. You will see that you are visiting the prod version because you see much less data.
=> Setup strict release workflow

src/components/includes/AddQuestion.tsx
=> Consistent characters-left wording

src/components/includes/CalendarHeader.tsx, src/components/includes/CalendarView.tsx
=> Show profile picture for the purpose of logout on mobile

src/components/pages/LoginView.tsx
Fix #299
The css change is probably dropped in a big merge.
=> Fix incorrect flex layout of showContact view in LoginView

src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionView.tsx, src/components/pages/ProfessorPeopleView.tsx, src/firehooks.ts
Fix #301.
Play with it on mobile
=> Fix invalid date error in `SessionInformationHeader` on mobile

src/components/pages/SplitView.tsx
=> Use loader instead of wrong placeholder text

src/components/includes/CourseSelection.tsx
Fixes flashing buttons issue by converting isNormalEditingMode. This delays switching editing mode to until after firebase respond/approves previous request to update the list of courses.
Previously, the error occurred because isNormalEditingMode was a normal variable, and it updated instantly on component re-render. Now, the update to isNormalEditingMode is delayed until server response.
You need isNormalEditingMode to be false initially (so start with 0 classes being enrolled). Select some classes and hit 'enroll'. There should be no buttons flashing. In addition, unenrolling from all courses should gracefully send you back to isNormalEditingMode=false (onboarding mode).
As such, this can't be tested if you're a professor of a course because you can't be unenrolled from that course. …
=> fix button flashing on course select in onboarding mode (isNormalEditingMode=false)

src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/pages/SplitView.tsx
With firebase realtime listening, we no longer need to limit the number of questions to reduce server-side load. With this change, we can fix #295.
Add more than 10 questions, no longer have the problem mentioned in #295.
=> Display all questions

src/components/includes/AddQuestion.tsx, src/components/includes/CalendarSessionCard.tsx, src/components/includes/CalendarSessions.tsx, src/components/includes/CalendarView.tsx, src/components/includes/ProfessorCalendarTable.tsx, src/components/includes/ProfessorOHInfoDelete.tsx, src/components/includes/SessionAlertModal.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionQuestion.tsx, src/components/includes/SessionView.tsx, src/components/pages/ProfessorDashboardView.tsx, src/components/pages/ProfessorView.tsx, src/components/pages/SplitView.tsx, src/components/types/fireData.d.ts, src/firehooks.ts, src/utilities/date.ts
- Private data is stored in a subcollection/doc at `/questions/{question}/content/private`
- Selectively load question data when isTA is flagged
(more coming soon)
What currently works:
- Student view
What is a WIP:
- TA view
=> Split public and private question data.

src/components/pages/AdminView.tsx
Just tweaked course id input label to say "course id"
No testing required. Label name change only.
None
=> Just tweak course id input label to say "course id"

src/index.tsx
It's causing too much trouble.
Relevant docs: https://create-react-app.dev/docs/making-a-progressive-web-app
=> Disable cache

src/styles/session/AddQuestion.less
Fixes #303 (uses a scroll bar instead)
Tested on Android (Chrome on a Moto G6) and desktop (Firefox)
=> Add Question Button CSS Fix

LICENSE
All contributors in the repo either signed CLA or their code is completely wiped out. Therefore, we can now license the code under AGPL-3.0
👀
=> License under AGPL-3.0

src/components/includes/SessionQuestionsContainer.tsx
If you ignore the comment, what this diff does is to essentially suppress the error. I write in the comment to justify what the error occurs and why it is safe to suppress it.
Try to add a question as a student. No errors!
Here is a diagram that explains the issue:
=> Fix the add questions permission error

package.json, src/components/App.tsx, src/components/includes/SessionView.tsx, types/react-web-notification/index.d.ts, yarn.lock
Adds a native desktop notification when a new question enters the queue. Use 'react-push-notification' to create a notification when.
Also solves issue #340 where a notification is pushed whenever the SessionView component re-renders, whether 1) a question is added (good), 2) web page is resized (bad), or session question state changes/is selected (bad). The problem with checking ```cachedPrevQuestions === questions``` is that, on re-renders, 'questions' is re-populated by objects from Firestore with the exact same data. So 'questions' is a different reference.
This solved by comparing the current list of question ids with the cached question ids in ```prevQuestSet``` - we only care if current list of `questions` has any new questionIds that the ```prevQuestSet``` does not have.
#####A …
=> Add a native destop notification when a new question enters the queue.

src/firebasefunctions.ts
Fixed an issue where only the students' 'role' for their course is being updated (and not the list of roles for that course).
Tested with the following procedure:
Find a list of 11+ emails that are originally not a TA or professor of the course (do not need to be enrolled). Add their names to the 'Import TA' prompt. The admin view should be populated with the nes TA names.
None
=> Fix error with course's list of roles (ta, prof) not updating in 'Import' feature

src/components/includes/AddQuestion.tsx, src/components/includes/Analytics.tsx, src/components/includes/CalendarDateItem.tsx, src/components/includes/CalendarDaySelect.tsx, src/components/includes/CalendarSessions.tsx, src/components/includes/CalendarView.tsx, src/components/includes/CalendarWeekSelect.tsx, src/components/includes/Popup.tsx, src/components/includes/ProfessorSettings.tsx, src/components/includes/ProfessorSidebar.tsx, src/components/includes/ProfessorTagInfo.tsx, src/components/includes/ProfessorTagsDelete.tsx, src/components/includes/QuestionsBarChart.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/includes/registerServiceWorker.ts, src/styles/calendar/CalendarDaySelect.scss
Unbreaks inputting tag name in "Manage Tags."
If you are a professor, switch to the Professor view. Add a tag in Manage tags. The website should not crash.
None
=> Unbreak tag name input in "Manage Tags"

src/components/includes/ProfessorOHInfo.tsx
Fixes #338 
* Tested with creating a new OH session
* Tested with editing an existing OH session
None
=> Prevent Duplicate TAs Assigned to the Same OH

src/components/includes/CalendarView.tsx, src/components/pages/SplitView.tsx
Fixes #342 
- Tested on mobile view 
- Tested on desktop view
None
=> Fix Infinite Loading Icon

src/components/pages/AdminView.tsx, src/constants.ts, src/styles/AdminView.scss
Updates term start date to 9/2 and end date to 12/21.
None
=> fix(AdminView): update term dates

.vscode/settings.json, src/components/includes/CalendarSessionCard.tsx, src/components/includes/ProfessorCalendarRow.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/ProfessorOHInfoDelete.tsx, src/components/includes/QuestionsBarChart.tsx, src/components/includes/SessionAlertModal.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/includes/UpdateProfile.tsx, src/components/pages/ProfessorPeopleView.tsx, src/components/pages/SplitView.tsx, src/components/types/fireData.d.ts, src/firebasefunctions.ts, src/firehooks.ts, src/styles/session/TASessionView.scss
Updates the type definitions and functions which handle session series.
Will expand, this is currently my first pass at adding the concept of "modality" to the codebase and an initial editing experience for professors.
We still need to facilitate Zoom link input.
None
=> Support virtual and in-person office hours.

src/components/includes/CourseCard.tsx, src/components/includes/CourseSelection.tsx, src/components/pages/LoginView.tsx, src/styles/courses/CourseCard.scss, src/styles/courses/CourseSelection.scss
Will expand - but we need to essentially "archive" courses which can no longer be accessed in the student view. This does that.
None
=> Clearly delineate former courses.

src/components/includes/AddQuestion.tsx, src/components/includes/CourseSelection.tsx, src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/types/fireData.d.ts, src/firebasefunctions.ts, src/firehooks.ts, src/styles/session/SessionQuestionsComponent.scss
This adds the necessary logic to handle sessions on the student side and properly update TA's session profiles on assigned questions.
None
=> Support virtual hours in student sessions.

src/components/includes/ProfessorOHInfo.tsx, src/components/includes/UpdateProfile.tsx, src/styles/professor/ProfessorOHInfo.scss
Offer more context to TAs and Professors when using our new modalities.
This adds modality descriptions when creating office hours _and_ adds more context for our virtual location feature.
Verify string changes in testing, move to production.
None
=> Clarify how modality works.

src/components/includes/ProfessorOHInfo.tsx
Fixes locations for single session locations.
Verified in team meeting.
None
=> Fix single session locations.

src/components/includes/AddQuestion.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/SessionInformationHeader.tsx
- Don't allow skipping location on hybrid.
- Remove character validation under hybrid modality.
- Fix locations under hybrid.
Test in testing instance!
None
=> Fix character limits and locations under hybrid.

src/components/includes/SessionQuestion.tsx, src/components/includes/SessionView.tsx
Don't display virtual location button in hybrid sessions.
Verify button is now hidden locally/in development.
None
=> Don't display virtual location button in hybrid sessions.

src/components/includes/AddQuestion.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/SessionInformationHeader.tsx
Clarify distinctions between Virtual/Hybrid/In-Person office hours & bugfixes. Thanks Evan!
None
=> Virtual/Hybrid/In-Person Office Hours fixes

firebase.json
So...
The old instance of queueme.in caches the index.html file from the old instance which causes the site to load the wrong JavaScript files and thus error out silently.
This would be fixed by the new instance, but because it is at `queueme.in` and not `www.queueme.in` it attempts to redirect the manifest loading and firebase hosting denies access because our CORS is not permissive for manifests.
In the dead of night we must deploy this to production and see if it fixes those with issues. It will have not effect on the testing instance.
None
=> Fix index.html caching issue.

src/components/pages/SplitView.tsx
=> Fix notification issues on mobile iOS.

src/components/includes/ProfessorCalendarRow.tsx, src/components/includes/ProfessorOHInfo.tsx
Hybrid previously technically still required a building location/room number for series.
Essentially, if you switch from virtual to hybrid and don't provide a location it can silently (albeit with a console error) error out.
1. Create a new repeating OH (virtual modality)
2. Verify it exists
3. Attempt to switch it to Hybrid
4. Verify the switch happened correctly
None
=> Fix 'hidden' issues with modality changes in series.

README.md
This was an exercise for the Intro to Git dev sesh.
None
=> Updated README with my name and role on QMI

src/components/includes/ProfessorOHInfo.tsx
Previously the session checkbox was shown for every office hour instance.
None
=> Only show session checkbox when its a session.

src/components/includes/CourseCard.tsx
I fixed the error where if a student clicks on an inactive class, it goes to the most recent class.
I just added a conditional statement.
I just added a conditional statement so that it only pushes a new page when the card is not inactive.
None
=> Bug fix for inactive classes

package.json, src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/types/fireData.d.ts, src/styles/session/SessionQuestionsComponent.scss, yarn.lock
TA comments have been implemented as per the design provided.
There are a few issues:
- No tooltip with "Comment" displays when mousing over the comment icon. Tooltips are difficult to get code in CSS so I'm leaving it out for now.
- No design was given for how TA comments will look on the student side. It will currently display as "TA Comment: <comment>" at the bottom of the question. This can be improved in future.
- I also used a different gray for the hover of the comment icon because the original gray was not contrasting enough.
- The comment icon is also different from the design icon because semantic UI only provides this comment icon.
- No notification is triggered when a TA issues a comment
New Features:
- Implemented TA comments
- Tested that TA can edit a comment, cancel a …
=> Implemented TA comments

src/components/includes/SessionQuestion.tsx, src/styles/session/SessionQuestionsComponent.scss
Fixed linter issues preventing master from building
None
=> Fix linter issues

src/components/includes/SessionQuestion.tsx
Implemented notifications for when TA comments or asker comments
Created new method componentDidUpdate() in component that implements notifications when TA or asker comments.
The method componentDidUpdate() is called whenever the props of the SessionQuestion component change. However, it only fires a notification when the TA comment or user comment is changed, and it only notifies the user and TA, respectively. An imported method addNotification() from react-push-notification is called with the necessary options to create the notification to the user.
- Sign into multiple windows as a TA and as a user
- Create a session, and create a question in the queue as a user
- Comment as a TA and see if a notification pops up for the user
- Comment as a user and see if a notification pops up for …
=> Jeremytacomments

src/components/includes/ProfessorTagInfo.tsx
…of parent tags
Fixes https://github.com/cornell-dti/office-hours/issues/407.
The problem: after creating a tag with children tags that are initially active or inactive, editing the active status of the assignment tag later would not change the active status of children tags. This could result in an inconsistent state where the assignment is active but the assignment children tags are not. Thus it would be impossible for a student to submit a question on that assignment.
However, there is still some bad data on the production database. The classes experiencing this issue are recommended to change the active status of a tag, hit save, and change the active status back (and hitting save again).
1. For classes where the parent/children tags are in an inconsistent active state: Change the …
=> Keep Active Status Children Tags In Sync With Assignment Tag

src/components/includes/ProfessorCalendarRow.tsx
Fixed bug with professor OH table having inconsistent width
Go to the Professor OH table and find that it has been fixed
None
=> Fixed issue 392

package.json
=> Fix CD issue

src/components/pages/SplitView.tsx
Added message to enable system notifications.
None
=> added message to enable system notifications

.github/workflows/release.yml, functions/yarn.lock
=> Fix CI/CD issue

firebase.json, functions/tsconfig.json
Fixed config issue with tsconfig preventing cloud functions from working
None
=> Fixed config issue with tsconfig

functions/tsconfig.json
=> Fix ci/cd 3

firebase.json, functions/tsconfig.json
=> Fixed tsconfig

src/components/includes/AddQuestion.tsx, src/components/includes/CalendarSessionCard.tsx, src/components/includes/ProfessorCalendarRow.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/ProfessorOHInfoDelete.tsx, src/components/includes/SessionAlertModal.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/pages/ProfessorPeopleView.tsx, src/components/types/fireData.d.ts, src/firebasefunctions.ts, yarn.lock
Started the feature for adding Zoom review sessions
I created an option for professors to add Zoom review sessions, which has a link to the Zoom review session and allows students to post questions. Professors are asked to input the name as well as the link from the add new office hour button. The Zoom review sessions are stored as a new type of FireSession, namely FireReviewSession, which has modality 'review' and a new property link, which is a string. 
I changed code in a lot of files to make this fix, including creating an ability to create a document in Firestore with this new type of FireSession and rendering this new type when a new review session is created. For now, I just added the review session link as an <a> tag below the cloud function statistics text, as I do not have a …
=> Added review session

src/components/includes/AddQuestion.tsx, src/components/includes/CalendarSessionCard.tsx, src/components/includes/ProfessorAddNew.tsx, src/components/includes/ProfessorCalendarRow.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/SessionInformationHeader.tsx, src/styles/calendar/CalendarSessions.scss, src/styles/professor/ProfessorAddNew.scss, src/styles/session/SessionInformationHeader.scss
I created a button to separate the add office hour and add discussion buttons. I also added a small redesign to the calendar view to show the type of the session i.e. whether it is an office hour or a discussion.
I created a new button, "Add new discussion" alongside "Add new office hour." This button allows you to create a new review session with a link. Now, the office hours and discussions are more distinguishable, as you can not create a discussion with the add office hour button, and vice versa. I also added a small redesign on the calendar view to show whether a given session is an office hour or a discussion. Finally, I added some small redesign touches to the discussion view by changing how the Zoom review link looks. I did not change too much for the discussion view design, as I …
=> Added new discussion button and redesigned modality

src/components/includes/AddQuestion.tsx, src/components/includes/SelectedTags.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/pages/SplitView.tsx, src/media/check.svg, src/media/uncheck.svg, src/media/yellowCheck.svg, src/media/yellowUncheck.svg, src/styles/SplitView.scss, src/styles/session/AddQuestion.scss, src/styles/session/SelectedTags.scss
Implemented the join the queue redesign. In this new design, the user no longer has to click on a button to be prompted with information to join the queue; these prompts are always displayed as long as the student hasn't already joined the queue. All the tags are displayed at all times, and the users can switch between assignments without having to unselect them first. The question text box is always visible, but it can only be edited once the user has completed all the required steps. 
- Select an assignment, then select a category. The question text box should become enabled. 
- Select an assignment, select a category, then unselect the category. The question text box should become disabled. 
- Select an assignment, select a category, then unselect the assignment. The question text box …
=> Implement join the queue redesign

src/components/includes/SessionQuestion.tsx, src/components/includes/SessionView.tsx
I don't like the way this library is set up but better to fix this quickly than leave iOS broken.
Ask our iOS testers to test before deploy.
None
=> Handle any Notification errors on iOS.

src/components/includes/DiscussionQuestion.tsx, src/styles/session/DiscussionQuestion.scss
Added a few small changes to the discussion session
I made the cursor become a clicker hand whenever it hovers over the upvote button, and I fixed a bug that allowed users to upvote questions after a session is expired.
- Make sure expired session questions can not be upvoted
- Check to see if hand becomes a cursor hand when it hovers over upvote
None
=> Small fixes for discussion session

src/components/includes/CSVUploadView.tsx, src/components/includes/ProfessorRolesTable.tsx, src/components/pages/AdminView.tsx, src/components/pages/ProfessorRoles.tsx, src/styles/index.scss, src/styles/professor/CSVUploadView.scss, src/styles/professor/ProfessorView.scss
Created the initial components for CSV upload in the professor view. This includes a 3 step process to allow professors to import TAs and other professors into a QMI course.
- some logic still needs to be added so that the _next_ button conditionally turns blue when the professor uploads a valid csv file
- made sure that all next and previous buttons lead to the appropriate view
- even though functionality is not there yet, the buttons don't crash, but instead but lead back to the manage roles table
- added CSVUploadView.tsx and CSVUploadView.scss
None
=> CSV Upload

src/components/includes/ProfessorTagInfo.tsx
Tag creation behaves oddly because list insertion and deletion doesn't work correctly when there isn't a unique ID for each element. Try adding and then deleting tags several times in the current UI and you can see the buggy-ness.
This utilizes a simple unique key generation technique to ensure tags function as expected.
Add and remove multiple tags without and with saving in the Add Assignment view and verify these bugs are fixed.
None
=> Fix tag creation UI bugs.

src/components/includes/CalendarDaySelect.tsx, src/components/includes/CourseSelection.tsx, src/components/includes/ProfessorCalendarTable.tsx
Are calendar components are currently complex beasts which maintain complicated nested object and array state, additionally they sometimes unnecessarily re-render, state breaks (and is hard to debug), and use deprecated lifecycle methods.
And this doesn't even mention our reliance on some scary date arithmetic!
Overall, it seems high time to clean this up for maintainability and sanity.
Ensure the modified calendar components work as expected.
None
=> Cleanup calendar components.

package.json, src/firebasefunctions.ts, src/test/time.test.tsx, src/utilities/date.ts, yarn.lock
Replace ad-hoc time computations with moment
Force office hours to be created in America/New_York timezone instead of system timezone
Fix issues around OH times shifted due to daylight saving time
Changes to code adding new OH and updating existing OH times
Test cases for helper function that generates the date range can be found in time.test.tsx
OH session generation code was tested manually.
None
=> Fix Daylight Saving Time Issues

package-lock.json, src/test/basic.test.tsx
=> remove slow test

src/components/includes/CSVUploadView.tsx, src/components/includes/ProfessorRolesTable.tsx, src/components/pages/AdminView.tsx, src/components/pages/ProfessorRoles.tsx, src/styles/index.scss, src/styles/professor/CSVUploadView.scss, src/styles/professor/ProfessorView.scss
Reverts cornell-dti/office-hours#463
=> Un-Revert "Revert "CSV Upload""

src/components/includes/ProfessorSidebar.tsx, src/components/pages/ProfessorDashboardView.tsx, src/components/pages/ProfessorPeopleView.tsx, src/components/pages/ProfessorRoles.tsx, src/components/pages/ProfessorTagsView.tsx, src/components/pages/ProfessorView.tsx
Don't maintain a "selected" array, let pages pass their type. The "selected" array was unnecessary and made state more complicated for no reason (and relied on indices, which isn't the most readable)
Verify all tabs of the professor sidebar continue to work.
None
=> Cleanup professor sidebar implementation.

src/components/includes/QuestionsLineChart.tsx, src/components/includes/QuestionsPieChart.tsx
This was just low hanging fruit from the `a11y` work, this pleases our linter and makes these components simpler.
Verify chart components continue to work as expected.
None
=> Convert simple components to functional style.

src/components/includes/CourseSelection.tsx
Fixes #464 by also tracking `numCoursesWithRoles`, which is the number of courses where the user is either a `professor` or a `ta`.
When not in normal editing mode (`!isNormalEditingMode` is when user is onboarding classes for the first time), we now use `numCoursesWithRoles` + `coursesToEnroll` + `coursesToUnenroll` === 0 as the check for whether user is able to "enroll"
Add an entry to pendingUsers, with a new email with all role assigned to all available classes this semester. Then log into QMI using this Google account (for the first time) and wait to get promoted to ALL available classes. The enroll button should still be available.
None
=> Fix edge case: newly-promoted pending TA/prof can't leave onboarding page.

README.md
Added Rose Zhou to list of collaborators of 2020-2021
=> added Rose Zhou to list of collaborators

src/components/includes/SessionInformationHeader.tsx, src/components/pages/SplitView.tsx, src/styles/session/SessionInformationHeader.scss
When a user tries to refresh or close the QMI, they will be prompted to confirm/cancel their action. 
(also fixed some minor css issues)
Try refreshing or closing the tab.
None
=> Prompt user to confirm/cancel before refreshing/closing window

src/components/includes/AddQuestion.tsx
Addresses issue #491. Converted AddQuestion from a class component to a functional component (to keep codebase more consistent). Removed class, constructor, public methods, etc. and replaced them with React hooks equivalent. 
Try adding a question by selecting different tags. There should be no breaking changes.
None
=> Convert AddQuestion component to functional React hooks

src/components/includes/LeaveQueue.tsx, src/components/pages/SplitView.tsx
=> Fix lint issues causing deploy check to fail

package.json, src/components/includes/SessionInformationHeader.tsx, src/styles/session/SessionInformationHeader.scss, yarn.lock
This pr fixes issues such as #499. The addition of the material ui grid system fixes the session header's appearance by allowing the size of header items to change as the screen size changes. 
Note: When checking out this branch, run `yarn` to install the new material-ui dependency.
This pr does not add any new functionality. 
When testing, make sure that the header items look good when you change your screen size. Try adding a long title or location when creating a new office hour session, the text should get cut off and there should be no stretching. 
None
=> Add material-ui package and fix session header using grid system

src/components/includes/Footer.tsx
=> add alt tag to footer

src/components/pages/LoginView.tsx
=> add more alt props

src/components/includes/SessionQuestion.tsx, src/firebasefunctions.ts
Removed the backend logic responsible for retracting a question, marking a question as resolved/no show/dont know, and commenting on a question from the SessionQuestion component to the firebasefunctions file.
- Remove a question you added 
- Mark a question you added as done (from TA side)
- Mark a question you added as no show (from TA side) 
- Comment on a question from both the TA and student side 
Additionally, you can check the question documents in firestore. The status field for each question doc should be updated accordingly.  
There should be no breaking changes. 
None
=> Refactor SessionQuestion backend logic

src/components/includes/AddQuestion.tsx, src/firebasefunctions.ts
This PR moves the backend logic for adding a question to the queue from the AddQuestion component to the firebase functions file.  
This PR does not introduce any new code. Try adding a question -- the functionality should be the same.
None
=> Move addQuestion backend logic to firebase functions file

src/components/includes/AddBlogPost.tsx
Merged blog post PR into master, then realized there was a style warning that causes compiling to fail.
Just a two line style fix (== -> ===, != -> !==) so not really any testing.
None
=> Fix style warning in blog post PR

src/components/includes/SessionView.tsx
PR #527 causes deploy check to fail. This PR fixes the warning. 
None
=> Add user dependency to the useCallback hook

src/components/includes/CalendarHeader.tsx
If you were to checkout `master` and change the following code in `CalendarHeader.tsx`
`const [showCourses, setShowCourses] = React.useState(false);`
to 
`const [showCourses, setShowCourses] = React.useState(true);`
You can see that there is a redundant, unused, and otherwise disabled menu:
| before | after |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/18223523/114255703-e7483780-9982-11eb-99b3-86308f0de370.png)  |  ![image](https://user-images.githubusercontent.com/18223523/114255751-35f5d180-9983-11eb-98a9-858eaecd427a.png) |
Just test that logout and feedback buttons work as normally. The removed code was a menu that did not display, so there should be no functionality changes.
None
=> Remove a redundant (and unused) logout menu.

src/components/includes/ProfessorTagsTable.tsx, src/components/pages/ProfessorDashboardView.tsx, src/components/pages/ProfessorPeopleView.tsx, src/components/pages/ProfessorView.tsx, src/firehooks.ts
Components that were refactored are:
- ProfessorTagsTable 
- ProfessorDashboardView 
- ProfessorPeopleView 
- ProfessorView
These components are responsible for displaying the professor side.
- Test the tags section of the professor view. You should be able to add and remove tags as normal.
- Test the people section of the professor view. You should be able to see data for the office hour session (should not tell you that there are no office hour session available to view)
- Test the dashboard view. You should be able to switch between tags. 
- Test professor view. Office hour sessions should be visible in the calendar view. 
None
=> Remove useEffect hooks that contain backend logic 

src/components/pages/ProfessorPeopleView.tsx, src/components/pages/ProfessorView.tsx, src/firehooks.ts
PR #535 introduces warnings that cause cd check to fail... we should probably add a build job to ci so we can catch these warnings before prs are merged into master 
None
=> Add missing dependencies causing cd check to fail in firehooks

src/components/includes/TopBar.tsx
The Logout Bar now disappears when users click off (as opposed to only when users click it again). Changed this in TopBar.
I tested on Firebase with yarn start. I also ran yarn lint to check for errors.
None
=> Logout Bar Click Off

src/components/includes/CSVUploadView.tsx, src/components/includes/ProfessorRolesTable.tsx, src/components/includes/ProfessorSettings.tsx, src/components/includes/ProfessorTagInfo.tsx, src/components/includes/ProfessorTagsRow.tsx, src/components/includes/ProfessorTagsTable.tsx, src/components/types/fireData.d.ts, src/firebasefunctions/courseSettings.ts, src/firebasefunctions/importProfessorsOrTAs.ts, src/firebasefunctions/tags.ts
Factors out all references to firestore.collection(...)... and `batch` in:
* src/components/includes/ProfessorTagsTable.tsx
* src/components/includes/ProfessorTagInfo.tsx
* src/components/includes/ProfessorSettings.tsx
* ProfessorRolesTable.tsx
* CSVUploadView.tsx
In addition, this PR adds the type NewData to fireData.d.ts.
Factors out all references to `firestore` in CSVUploadView.
So far only removed logic out of tags and related components.
This updates fireData.d.ts.
None
=> Removing Firebase Logic Out of Some Components

src/components/pages/LoginView.tsx, src/styles/Footer.scss, src/styles/login/LoginView.scss
Worked on landing page redesign and made small changes to the footer to make it look more centered.
I worked on the new landing page redesign for both desktop and mobile devices. I also made the text in the footer look more centered vertically.
- Make sure new redesign looks good on both desktop and mobile devices
- Make sure footer looks centered vertically as I described
None
=> Landing page redesign

src/components/includes/CalendarView.tsx, src/components/includes/CourseSelection.tsx, src/firebasefunctions/calendar.ts, src/firebasefunctions/courses.ts
Firebase logic is removed from the calendar and course files into their own files under the firebase functions folder.
I tested changes by adding and removing courses as well as interacting with the calendar, as the changes were small by moving a few lines of code into other files.
=> removed firebase logic from calendar files

src/components/includes/ProfessorCalendarRow.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/ProfessorOHInfoDelete.tsx, src/firebasefunctions/session.ts
I moved Firebase-related code from some professor files into a new file session.ts within firebasefunctions.
I moved code that either changed or read data from Firestore in the files ProfessorCalendarRow, ProfessorOHInfoDelete, and ProfessorOHInfo into a new file session.ts. I was also asked to move code that changed or read data from ProfessorDelete and CalendarDateItem, but I did not find anything in particular in those files that did either of those operations. If I missed something related to either of these operations in these files, please let me know!
Note that for all of these tests (except the last bullet point since it doesn't really apply), I am talking about a **single** office hour and not repeated office hours.
- Try adding an office hour and see that it is added on …
=> Move Firebase-related code from some professor files into a file within firebasefunctions

src/styles/SplitView.scss, src/styles/TopBar.scss, src/styles/calendar/CalendarHeader.scss, src/styles/courses/CourseSelection.scss
Adresses #546 
Cleaned up mobile UI view:  got rid of horizontal scrolling on the homepage, fixed the top bar (which was stretched in prof view), centered classes, etc.
<details>
<summary>Here are images of the mobile UI before</summary>
<br>
</details>
<details>
<summary>Here are images after</summary>
<br>
</details>
Run the app, make sure the mobile home view looks decent (there is no horizontal scrolling, etc.)
None
=> Fix home view in mobile UI 

src/components/includes/ProfessorStudentToggle.tsx, src/styles/calendar/CalendarHeader.scss, src/styles/professor/ProfessorSidebar.scss
Addresses #478 
Changes the display of the dashboard/queue options on the professor's side from a pop up menu to a toggle bar to match the final top bar design from last semester which can be found [here](https://www.figma.com/file/h0kMHuGjX9QCtZ0Y6rUbDj/Fall-2020?node-id=709%3A143).
Sign in as a professor, toggle between queue and dashboard, make sure you are redirected to the right page. 
Also, make sure the top bar looks decent on mobile devices. 
None
=> Change Queue/Dashboard to toggle

src/components/includes/Footer.tsx, src/styles/login/LoginView.scss
Removes future merge conflict in README.md. Please approve!
None
=> Merge release into master

src/constants.ts
As in title. Allows the ILR Office of Student Services Drop-In Hours "course" to continue operating through the summer semester.
Testing plan not required because it is a one-liner change in `constants.ts`
None
=> Update SP21 Semester End Time to 08/25

package.json, src/test/local/courses.test.tsx, yarn.lock
This PR creates the first firebase function unit test.  It tests the `updateCourses` firebase function which is found in `firebasefunctions/courses.ts`. The calls to firebase such as `docs`, `collection`, etc. have been mocked, and the function has been tested given a dummy user. Now, that this test has been created, unit tests for the remaining firebase functions can be created easily because this test can be used as a reference.
run `yarn test` and you should see that the `updateCourses` test is passing
None
I ignored the expected return types of the mocked objects to be able to replace them with simpler types which makes testing the functions easier.
=> Create first firebase function unit test

src/test/local/calendar.test.tsx, src/test/local/courseSettings.test.tsx, src/test/local/courses.test.tsx, src/test/local/session.test.tsx
Created unit tests for `calendar`, `courseSettings`, and `session` by mocking the database and making sure that the database method calls are being done correctly (pass in the right arguments, and get called once). 
run `yarn test`
None
=> Add more unit tests 

src/constants.ts
Changed sem to SP22
Make sure the test course I created for the new semester shows up!
None
=> New semester!!

functions/package.json, functions/src/index.ts, src/components/includes/CSVUploadView.tsx
Jeremy noted at the beginning of the semester that there was an issue with adding users by CSVs such that roles were added to the user object but the users were not added to the role arrays for the course, thus preventing them from doing a lot of restricted actions bound by security rules, such as adding tags.
I located two issues in the onUserCreate function:
1. The mapping function for courses where the user is a professor used taCourseIds instead of profCourseIds, which meant that the course was always undefined and the user was never added
2. When adding users to the array for the course, the array was set such that it overwrote all existing data (tas= [userId]).
Based on my testing, these have both been rectified. 
IMPORTANT NOTE: I have pushed the changed function to QMI-test, but …
=> Fixing bug in cloud function onUserCreate

functions/src/index.ts, src/components/includes/CSVUploadView.tsx
Pushes very important bug fixes to production
- Make sure importing professors/TAs works as desired, and try testing pending users to see if when a pending user creates an account, the list of TAs and professors is still as expected (see #605 and #606)
None
=> Important bug fix for importing TAs/professors and pending users

src/styles/calendar/CalendarSessions.scss
Changed ahead to red and finished to green.
- check the colors
None
=> change color

src/components/includes/AddQuestion.tsx, src/components/includes/SessionQuestion.tsx, src/components/types/fireData.d.ts, src/firebasefunctions/sessionQuestion.ts, src/styles/session/AddQuestion.scss, src/styles/session/SessionQuestionsComponent.scss
I added a checkbox to indicate if you are virtual or in-person for hybrid office hours. This shows as a badge on the TA side.
- Check to see that the checkbox is there and that both checking and unchecking options work
- Check to see that the TA can see the badge
None
=> Adding badges for in-person and virtual for hybrid office hours

src/components/includes/AddQuestion.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionQuestion.tsx, src/components/types/fireData.d.ts, src/firebasefunctions/series.ts, src/styles/professor/ProfessorOHInfo.scss
I added an option when creating a hybrid office hour that allows the course to provide the zoom link. This is represented by the main office hours screen which tells the student to go to the course to find the zoom link. 
You can create this new type of office hour by checking the "Use course zoom link" box on the hybrid office hour create screen as a professor role.
- Test in-person, virtual, and both types of hybrid office hours (course provided zoom link checked and unchecked) and **_make sure_** that they work. You can do this by adding a question as a student for all types of office hours, as I did change the state machine a little bit for this PR, as well as try assigning and answering questions as a TA
- Test hybrid with both series as well as for an individual session for the …
=> Added new type of hybrid office hour with TA zoom link

src/components/includes/AddQuestion.tsx
Allows students to add location in the case where there is no tags.
- Make sure you can add questions as expected for all three (four, including the new hybrid type) office hour types without any tags
- Make sure you can see the checkbox for the new type of office hour without any tags
None
=> Very minor fix for location bug

src/components/includes/ProfessorTagInfo.tsx, src/styles/professor/ProfessorTagInfo.scss
When creating or editing an assignment, you must have a tag now. A warning message in red text shows up if you try to create or edit an assignment so that it no longer has any tags.
- Test to see that you can not create an assignment without a tag, or edit an assignment so that it no longer has any tags
- Test to see that you see the red warning message pop up when doing so
None
=> Added fix for having no tags under assignment

src/components/includes/TopBar.tsx, src/components/includes/TopBarNotifications.tsx, src/firebasefunctions/notifications.ts
Adding additional checks to notificationList to avoid undefined error being thrown
On session view, click on the notification bell. Then, tab between session view and dashboard a couple times. Hopefully no error thrown. The other error I have not been able to reproduce but Michelle can test out opening the test site once we push.
None
=> Removing undefined error (hopefully)

src/components/includes/SessionQuestion.tsx, src/styles/session/SessionQuestionsComponent.scss
Added tooltip with queue position.
- Hover over queue position and check that tooltip with correct position is displayed.
None
=> Added tooltip

src/components/includes/CalendarExportModal.tsx, src/components/includes/CalendarSessionCard.tsx, src/components/includes/CalendarSessions.tsx, src/components/includes/CalendarView.tsx, src/components/pages/SplitView.tsx, src/styles/calendar/CalendarSessions.scss
This PR adds a feature to export an entire day of office hours to Apple Calendar. Above the list of office hours on the left side of the screen, I added the date and a calendar icon to export the office hours for the day. Clicking the icon should open the calendar export modal, where the user can choose to export the office hours to Apple Calendar. I could not find a way to export an entire day of events to Google Calendar, so only the Apple Calendar option is shown. I also updated the title of the calendar export modal for a single office hour session to include the course name and OH name. 
- Check that the correct date is displayed for the selected day of office hours. 
- Try adding multiple office hours to the same day and exporting them at the same time using the day export feature …
=> Calendar day export

src/components/includes/ProfessorOHInfo.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/types/fireData.d.ts, src/firebasefunctions/series.ts
I added the course zoom link checkbox when creating online office hours, which will cause it to display "Use course zoom link" for online office hours with this property. This was developed with CS 4410 in mind, as they have a course zoom link that they use for online office hours.
- Try creating an online office hour both as a singular office hour and as a series, and check the "use course zoom link" checkbox---make sure both TAs and students see the "Use course zoom link" next to the zoom icon in the office hour. Furthermore, try not checking the box for both singular and series for online office hours to see if the original zoom link feature is still there (i.e. TA writes zoom link in box, student can click join to join the office hour when they are assigned)
- Make sure hybrid and …
=> Added course zoom link option for online office hours

package.json, yarn.lock
Attempting to fix build failure by adding twilio to top-level package.json.
None
=> adding twilio to package.json

functions/src/index.ts
Last night, I deployed several updates to the firebase functions to prod to fix a bug. This is a PR to make sure those changes are  on github as well as on firebase.
- Added .catch()es to every notificationTracker update so that users without notificationTrackers can create them and won't throw an error
- refactored some code
- Delete your notificationTracker in the database, and ensure that notifications send normally
- ensure that notifications send normally with a notificationTracker too
None
=> Updating master with firebase function changes

.github/workflows/stanford.yml
=> changing yml back

.github/workflows/stanford.yml
=> another yml fix

.github/workflows/cd.yml, .github/workflows/release.yml, .github/workflows/stanford.yml, package.json, src/firebase.ts
=> Fixing environment variable keys

.gitignore, src/components/App.tsx, src/components/includes/AddQuestion.tsx, src/components/includes/AdminCourseCreator.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionView.tsx, src/components/pages/SplitView.tsx, src/constants.ts, src/firebase.ts
Leaving the comments bug for later because I cannot reproduce it.
- fixing some console errors related to nesting \<p> tags within \<p> tags, not unsubscribing a subscription on unmount
- Updating the semester to summer and setting relevant dates
- adding support for a local .env file specifying the test api key
Test that the database connects correctly with a specified .env file. Check that the console fixing changes don't change the site. observe that the semester has changed.
None
=> Update semester, fix console errors, add local env variable

src/components/includes/Banner.tsx, src/components/includes/CommentsContainer.tsx, src/components/includes/CourseSelection.tsx, src/components/includes/SessionQuestion.tsx, src/components/pages/SplitView.tsx, src/firebasefunctions/series.ts, src/firehooks.ts
Swapping the snapshot to a firehook.
Open the console. Make a question, ensure no errors appear. Add comments from both a TA and student, and ensure both appear in real time. Delete and ensure the same.
None
=> Fixing the comments bug

src/components/includes/CommentsContainer.tsx, src/components/includes/CourseSelection.tsx, src/components/includes/SessionQuestion.tsx, src/components/includes/UserComment.tsx, src/components/pages/SplitView.tsx, src/firebasefunctions/sessionQuestion.ts, src/firehooks.ts
=> Comments fixes to master

functions/src/index.ts, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/ProfessorPendingTable.tsx, src/components/includes/ProfessorRolesTable.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/pages/ProfessorRoles.tsx, src/components/types/fireData.d.ts, src/firehooks.ts, src/styles/session/SessionInformationHeader.scss
In discussion with 4410 and 2110, a couple of issues/ambiguities were raised. These were:
- Ambiguity with what "pending" means--it seems like the operation to add users is in progress, but the pending message disappears on refresh, so then it appears it has failed because the names are never added
- inability to add a course link to a session when "use course link" is selected
- Creating a session series without a name fails without a descriptive error message, while creating a session without a name simply works
I've implemented the following solutions, in order:
- Changed the "pending" message to "pending account creation", and added a second table to the manage roles tab that shows which emails are pending and for which roles
- added a course link to the sessions, such that if "use …
=> Various Fixes from early semester feedback

src/components/includes/ProfessorOHInfo.tsx, src/components/includes/SessionInformationHeader.tsx
Adding a quick fix for editing office hours that already have a course zoom link enabled/entered.
None
=> Fixing editing office hours with course zoom links

src/firebasefunctions/notifications.ts
Adding a small set of comments to provide clarity for an ambiguous notifications function.
None
=> Commenting notifications code

src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/firebase.ts, src/styles/session/SessionQuestionsContainer.scss
This PR allows professors to view which TA is assigned to each question. Previously, professors and TAs could only view unassigned questions and questions assigned to them. I added a third section on the professor view that includes all assigned questions, allowing professors to see who is assigned to which question.
Since there may be a large number of assigned questions, the "All Assigned Questions" section is collapsible to avoid cluttering the session page. 
When professors assign themselves to a question, this question will be included in the "Assigned to Me" section instead of the "All Assigned Questions" section so professors can easily see which questions they are assigned to. 
With this new view of all assigned questions, professors can now unassigned TAs from questions. …
=> Professor view of all assigned questions

src/firebase.ts, src/firebasefunctions/importProfessorsOrTAs.ts
Last year, there were multiple occasions where professors accidentally demoted themselves or other head TAs by including them in their list when updating roles via import. This PR prevents role demotions (professor to TA) when updating roles via import. 
I tested the fix by checking that a user cannot be demoted from professor to TA when updating roles via import (both entering manually and uploading csv file). I also made sure that demotions can still be done using the role dropdown option. Additionally, a user's role can still be updated from TA to professor using the import option. 
None
=> Professor Demotion

src/components/includes/CalendarHeader.tsx
Adds navigation for the admin and product updates pages for admins in the navbar.
Test the navigation buttons as an admin. Test they do not appear if you are not an admin.
None
=> adding navigation for admin and product updates

.github/workflows/cd.yml, .github/workflows/release.yml
Build is crashing because there is not enough memory. Given that build succeeds locally, I believe this is simply because the github node variable for max memory is too low for our project now. I adjusted it in our workflows to attempt to fix it.
None
=> tweaking node memory variable

src/constants.ts
=> Change the semester for the spring

package.json, src/components/includes/ImportRolesModal.tsx, src/components/includes/SessionView.tsx, src/components/includes/TaAnnouncements.tsx, src/firebasefunctions/session.ts
=> fixing lint errors and cyclic dependency

src/components/includes/AdminReadOnlyCourseCard.tsx, src/components/includes/QuestionsLineChart.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/pages/ProfessorPeopleView.tsx, src/components/types/fireData.d.ts
This PR makes changes to the existing Analytics page. The following changes are made: 
- There is a new section added which shows the average wait time per day 
- If there are multiple sessions a day, the data points are shown as 1 and the average wait time is the aggregate value 
- Date picker's undefined error is removed 
- The existing bar graph is removed 
** I need some feedback on the design since there is a big empty space from removing the initial bar graph. 
None
=> Updates on Analytics Page

README.md
Added my name to the list of contributors in the README.md
None
=> Add name to contributors in readme

src/components/includes/ProfessorCalendarRow.tsx
Replaced the 'x' with a trash can icon for deleting office hours in Professor Dashboard view.
Tested by creating, editing, and deleting office hours in Professor Dashboard view.
None
=> Add trash can icon for deleting office hours

src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionTime.tsx, src/styles/session/SessionQuestionsComponent.scss
Displays the current minutes and seconds spent on a question to the assigned TA. Starts at the assigned time and ends time if unassigned, or marked as no show or done by TA.
Tested by creating question in student view, and then assigning, unassigning, marking as no show, and marking as done in TA view.
If the question character length reaches the end of the question box, the question time will be pushed out of the box. However, most professors limit the question length, and most student's questions don't reach this length.
=> Add current question time

src/components/includes/ProfessorRolesTable.tsx
Admin used to use (mostly) the default roles table. Updated it to allow mutating your own role if you are in admin view.
None
=> Let admins change their own roles

src/components/includes/LatestComment.tsx, src/components/includes/LatestCommentContainer.tsx, src/components/includes/SessionQuestion.tsx, src/media/expandPreview.svg, src/styles/session/UserComment.scss
For every session question with comments/messages, if the reply chain is collapsed, then a preview of the latest comment is shown below the question. The preview is highlighted yellow for a student if a TA has added a message after they last opened the reply chain, and the preview is highlighted yellow for a TA if a student has added a message after they last opened the reply chain. This highlight goes away once the student/TA opens the reply chain/views the new message. There is also an expand button next to the preview that functions the same as the reply button.
Example of student view before opening reply chain:
Example of student view after opening reply chain and closing again:
Example of TA view before opening reply chain:
Example of TA view after opening reply chain and closing …
=> Add latest comment preview to session questions

src/constants.ts
updating new semester constants
None
=> update start/end date for new semester

src/constants.ts
changed start date from 8/21 to 8/16 so course creation can be done before classes start
None
=> small change to start date

src/components/includes/AdminCourseCard.tsx
Added documentation for `AdminCourseCard` in `src/components/includes/AdminCourseCard.tsx`
=> add documentation for AdminCourseCard

package.json, src/components/includes/SessionQuestion.tsx, yarn.lock
This PR makes any links in the session question content become clickable and open in a new tab.
Example:
- before (ta view):
> <img width="960" alt="Screen Shot 2023-09-17 at 12 21 21 PM" src="https://github.com/cornell-dti/office-hours/assets/45403687/6fb03c45-578f-4e3a-8b11-033a0a1e353e">
- before (student view):
> <img width="961" alt="Screen Shot 2023-09-17 at 12 21 39 PM" src="https://github.com/cornell-dti/office-hours/assets/45403687/1a8bc55f-66da-48c9-ba25-2aa3120cfc89">
- after (ta view):
> <img width="966" alt="Screen Shot 2023-09-17 at 12 20 47 PM" src="https://github.com/cornell-dti/office-hours/assets/45403687/38639aab-8908-4d1a-b74f-edfcbc38d99d">
- after (student view):
> <img width="966" alt="Screen Shot 2023-09-17 at 12 20 59 PM" …
=> Make links in session questions clickable

src/firebasefunctions/importProfessorsOrTAs.ts
Add documentation for `addOrRemoveFromRoleIdList` in `importProfessorsOrTAs.ts`.
None
=> Add documentation

src/constants.ts
changing course start and end constants for sp 2024
None
=> Update constants.ts for sp2024

src/components/includes/TopBarNotifications.tsx, src/styles/blogPosts/Notifications.scss
- fixed notifications dropdown styling so that it matched the user profile dropdown (picture below) more closely 
- mainly just changed font and the box css
- may need to double check with design to make sure it is ok 
- tested by creating different notifications and seeing if it looked ok on the frontend (see some scenarios below)
- may need to reconsider notifications design in the future if really want to align the designs because it is pretty different from the user profile dropdown 
None
=> Fix Notifications Styling

src/components/includes/TopBar.tsx, src/styles/TopBar.scss
Made the QMI logo clickable, so that when it is clicked, it redirects the user to the "/home" page.
Tested clicking the logo on different screen sizes (mobile, computer, tablet).
Made the logo have an underline on hover. Also changed the user profile underline hover behavior to be consistent in style with the logo hover style.
None
=> Made logo clickable to go to the home page

README.md
Added my name to contributors, changed last updated date
N/A
=> Added new developer to contributors

README.md
Added Lucy and Sia to the list of contributors on the README
QMI still works
None
=> Update README with SP24 Designers 

package.json, src/components/App.tsx, src/components/includes/CalendarDateItem.tsx, src/components/includes/CalendarWeekSelect.tsx, src/components/includes/DiscussionQuestion.tsx, src/components/includes/ProductUpdates.tsx, src/components/includes/ProfessorCalendarRow.tsx, src/components/includes/ProfessorDelete.tsx, src/components/includes/ProfessorOHInfo.tsx, src/components/includes/ProfessorTagInfo.tsx, src/components/includes/SelectedTags.tsx, src/components/includes/SessionAlertModal.tsx, src/components/includes/SessionInformationHeader.tsx, src/components/includes/SessionQuestion.tsx, src/components/includes/SessionQuestionsContainer.tsx, src/components/includes/SessionView.tsx, src/components/includes/TopBarNotifications.tsx, src/components/pages/SplitView.tsx, src/firebase.ts, src/firebasefunctions/notifications.ts, src/firehooks.ts, yarn.lock
Upgraded TypeScript to v4.1.6
Some notes on changes:
Added the 
`"**/@typescript-eslint/eslint-plugin": "^4.1.1",`
`"**/@typescript-eslint/parser": "^4.1.1"`
lines to resolve the `0:0  error  Parsing error: Cannot read property 'map' of undefined` linting pipeline error we see from upgrading TS
That brings up a whole host of new (but more fixable) errors. From there, it's a matter of going file by file to ensure everything is strongly typed and using the newer anonymous function type annotations, rather than the older `Function` annotation.
No more errors, even momentary ones that disappear, when running locally. Normal QMI functions work as intended.
None
=> Upgrade TypeScript to v4.1.6 

.github/workflows/release.yml
upgrading node in .yml file to 16
None
=> change node version to 16

functions/package.json, yarn.lock
=> upgrade firebase for node version compatibility

functions/yarn.lock
=> update firebase cli

functions/package.json, functions/yarn.lock, package.json, yarn.lock
=> Upgrade Firebase Tools and TS in Functions

package.json
=> downgraded firebase cli to a compatible version

package.json
=> firebase tools to v11

src/constants.ts
Set current semester to FA24 with start date 8/19 and end date 12/20
=> Update constants.ts for fa2024

src/components/includes/ProfessorOHInfo.tsx, src/firebasefunctions/series.ts
Deploy [this](https://github.com/cornell-dti/office-hours/pull/866) PR that fixes a bug with saving Zoom links for recurring OH
None
=> fix virtual series ta link not saving

src/components/includes/ProfessorOHInfo.tsx
Provide a non-undefined string fallback for TALink. Same fix as [this PR](https://github.com/cornell-dti/office-hours/pull/818) but for the useEffect TALink update, in addition to just the state initialization.
None
=> Fix Undefined TA Link Update

src/components/includes/UserComment.tsx, src/styles/session/SessionQuestionsComponent.scss
Changed display of Questions from flex since Linkify makes each link a new component. Change in formatting shouldn't really affect comments in the future because comments have a character limit anyways. 
Linkified comments for both students and TA's 
TA View:
Student View:
Latest comment preview is intentionally not linkified:
None
=> Format links and linkify comments

src/scripts/wrapped-fa24.ts
Initial version of a script to populate QMI wrapped collection.
None
=> wrapped script v1

src/components/includes/ProfessorTagInfo.tsx, src/styles/professor/ProfessorTagInfo.scss
Deploying [this PR](https://github.com/cornell-dti/office-hours/pull/880) to prod
None
=> Tag UI fixes

src/components/includes/SessionView.tsx
Disable a potentially overactive collections snapshot listener
Normal QMI functionality works
=> Disable Questions Monitoring

src/components/includes/SessionView.tsx, src/components/pages/SplitView.tsx
- disable react hooks exhaustive deps (probably a temp solution)
- delete some extra console logs
- follow-up to [this pr](https://github.com/cornell-dti/office-hours/pull/888) that was failing build in master
None
=> Fix Questions Monitoring Build Issue

README.md
Completed my newbie pr as my first dev portfolio! I added my name as part of the list of contributors on the README for the 2024-25 year.
=> update README for 2024-25 add Annie (newbie pr)

src/components/includes/TopBar.tsx, src/components/includes/TopBarNotifications.tsx, src/components/includes/WrappedCountdown.tsx, src/components/pages/SplitView.tsx
This is a follow-up PR since the last deployment of the countdown PR <a>https://github.com/cornell-dti/office-hours/pull/893</a> that addressed minor bugs listed below:
- Add an extra check `user.wrapped`, so countdown only gets rendered if wrapped data exist
- Fixed the grammatical singular and plural form of DAY(S), HOUR(S), MINUTE(S)
- Allow wrapped notification to be clickable to open wrapped modal
- Previously having `timeRemaining` in the dependency array of `useEffect` to update the countdown results in an infinite render, thus added a timer that will update the countdown every 1 second interval
Tested the changes on local server
e changes on local server
https://github.com/user-attachments/assets/8a5fe137-2b40-44ea-b9e4-fd60d5fae901
None
=> Countdown Component Fixed Minor Bugs

src/components/includes/Wrapped.tsx, src/styles/Wrapped.scss
- fixed bug with how wrappedData was stored from collection, it should now show correct numbers
- changed "semester" words to "year" in ui
- added white hover to dots to make it easier to see you can click
- fixed hover on arrows to resemble the close icon
- If we're considering mobile users, anything below 800 px you can't easily exit Wrapped or click to other slides
800px:
700px:
None
=> Testing + small css fixes

src/components/includes/TopBarNotifications.tsx, src/components/pages/SplitView.tsx
Only display these two components if hasWrapped === true
=> Hide Countdown & Ribbon Notif if user doesn't have wrapped

package.json
=> remove node legacy options

.github/workflows/release.yml
=> downgrade release.yml to node v16

src/components/includes/TopBarNotifications.tsx
make `hasWrapped` and `countdownZero` a condition for the notification bell being displayed
None
=> fix missing notification bell

src/components/includes/Wrapped.tsx
Add parameters to NumberPeople so that different numbers can be inputted rather than defaulting to totalMinutes.
Made totalMinutes and numStudentsHelped different.
None
=> Add parameters to NumPpl - Release

src/components/includes/TopBarNotifications.tsx, src/components/includes/Wrapped.tsx, src/styles/Wrapped.scss
Title
Deploys the UI changes in the following PRs:
- https://github.com/cornell-dti/office-hours/pull/916
- https://github.com/cornell-dti/office-hours/pull/917
QMI Wrapped works as expected
=> UI fixes n bugz

src/components/pages/SplitView.tsx, src/constants.ts
Cherry pick for this PR: https://github.com/cornell-dti/office-hours/pull/919
None
=> Updating constants.ts & disabling wrapped for spring 2025

README.md
Updated 2024-2025 team members' name
None
=> Layla/ Updated Team members name

.github/workflows/release.yml
Trying to fix this deployment issue:
None
=> bump release node v20

firebase.json, functions/src/index.ts
=> add node runtime and fix warnings

firebase.json
=> downgrade node16 runtime in firebase.json
