- package.json
- Moved `yarn run deploy` (client-building step) to the post-install step from the start step so that it doesn't rebuild on each restart
> Adjusted Heroku client build step

- docs/database.md
- server/index.ts
- server/office_hours.sql
- Fixes the authentication flaw in #61 by only allowing the server to call `api_find_or_create_user`
- Adds a database trigger to the courses table, which adds every existing user as a student whenever a new course is inserted
- Updated database documentation with these changes
> Authentication Patch

- client/src/components/includes/CalendarView.tsx
- server/index.ts
Now you will no longer get the `Cannot GET /foobarroute` when the route doesn't exist and the service worker hasn't loaded, it just loads our react app. The two lines in index.ts seem necessary for some reason. 
Other than that, I just removed a redundant tag that was causing rendering errors in safari. (Accidentally introduced in my last PR)
> Add routing forwarding and fix safari bug

- server/database/migrations/0002_fix_aws_roles.sql
- Error in staging after deploying #74: could not `set role to backend` when the server started
- Fix: grant the default user (`postgres`) the permission to switch to the `backend` user
- Applied in staging and production; it is not required locally, and in fact does not appear in pg_dump (I'm guessing because `postgres` is already a superuser and does not need to be explicitly granted any permissions)
> Database Migration 0002: to fix AWS roles issue

- docs/database.md
- server/database/migrations/0002_fix_aws_roles.sql
Fixes a small bug in migration 0002 that made it fail in production. In short, the username in production is `ohprod1`, whereas it is `postgres` on staging (and usually on local as well).
* Updated migration 0002 and applied it to production -- staging and local remain unchanged
* Updated database docs with some authorization details that were not documented in a previous PR
As far as this particular SQL statement goes (`GRANT backend TO...`), note that it doesn't need to be part of `mock_database.sql`. This is because roles are managed outside of a particular database schema; roles exist at the database level. Essentially, roles are a one-time setup, and you can change the schema independently of them. While setting up a database locally for the first time, a developer on the team will …
> Fixing up 0002 for production

- client/src/components/includes/ProfessorOHInfo.tsx
- client/src/components/pages/ProfessorView.tsx
Gives the ability to assign no TAs to an office hour
* Adds an option to deselect a TA from the dropdown
When saving changes of an existing session/series, the old info remains in the editor, including any unselected TA fields. In general, it might be best to requery all of the info for a particular session when saving changes and canceling edits so that any changes are reset.
> Unselect a TA

- client/src/components/App.tsx
* Rather than just defaulting to 5, first try redirecting users to the saved course in localStorage, if that doesn't exist then redirect them to courseId 5.
> Default courseId uses localStorage then 5 as fallback

- client/src/components/includes/SessionQuestionsContainer.tsx
Fixes the issue where the notification only shows if the user's question is the absolute first question in the queue, even if the questions ahead are all in progress.
* Subtracts number of questions in progress from the user's position to reflect the position more accurately
> "Your question is up!" Notification Fix

- .github/workflows/ci-workflow.yml
Install and Build in the CI script is failing for yarn with the following error:
```
Install and Build1s
##[error]Process completed with exit code 1.
Run yarn install
yarn install v1.18.0
[1/5] Validating package.json...
error office-hours@1.0.0: The engine "node" is incompatible with this module. Expected version "10.16.3". Got "10.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]Process completed with exit code 1.
```
Modified CI script so yarn ignores the node version.
Run the CI.
David was here.
> Yarn ignore incompatible node version

- client/src/components/includes/SessionQuestionsContainer.tsx
- client/src/components/includes/SessionView.tsx
- client/src/components/types/appData.d.ts
- client/src/styles/SplitView.less
* Allows user to click on the text that says "You are holding a spot in another active queue...." to remove their question in the other active queue. After, the join the queue button will be clickable and the other text will disappear.
* Tested locally by adding joining a class's queue and then changing classes to get the "You are holding..." text to display, then pressed the text and added a question to the queue.
* Need a way for testing what other uses see when someone removes their question to join a different queue.
* A list of question ids are passed into SessionQuestionsContainer, but we only remove the first index/first question id. There shouldn't be a case where the list has length greater than one, but if that ever comes up, we would need to either add a database call that …
> Leave Other Queues

- .github/workflows/ci-workflow.yml
- client/package.json
- package.json
- server/package.json
We pinned yarn to 1.18 in #147 since yarn 1.19 has a bug that randomly causes install to fail. Now yarn has released 1.19.1 and it's already widely available in many environments. Therefore, we should now target `>=1.19.1` instead.
CI still passes.
> Use latest yarn

- client/src/components/App.tsx
- client/src/components/includes/CalendarHeader.tsx
Changed front-end to display only SP20 classes instead of FA19. Changed default class id (if user is new to QMI) from 5 to 8
* fix the blank page attempting to display course 5, which is inactive
* changed "FA19" to "SP20" in CalendarHeader.tsx
> Broken Class Id and Semester fix

- .github/workflows/ci-workflow.yml
Setup a CI job to warn against big diff, powered by [big-diff-warning](https://github.com/cornell-dti/big-diff-warning)
See the PR comment. Bot comment should be there.
> Setup CI job to warn against big diff

- client/src/components/includes/SessionInformationHeader.tsx
* When professors create a new office hour and don't select any TAs for that session, the front-end was accessing the first index of an empty list in SessionInformationHeader. In previous semesters, this did not cause the site to crash so it was dealt with previously.
* The fix was to deal with it on the front-end by removing the component's state because it is unnecessary. Logic was added to deal with an empty list, so now we are not going out of bounds. 
This used to not break before but at the start of SP20, it suddenly broke. The cause was not determined, but the fix was to update SessionInformationHeader to deal with the backend case mentioned above.
> Fix Crash For No TAs Session

- .github/workflows/ci-workflow.yml
- client/package.json
This diff no longer pins Yarn 1.18 in develop-firebase branch. This is introduced when Yarn 1.19.0 has a breaking change. Now the latest yarn fixed the problem, we no longer need this.
> No longer pin yarn to 1.18

- client/src/components/includes/ProfessorOHInfo.tsx
- server/index.ts
- server/package.json
- server/yarn.lock
Allows you to select office hours in 10-minute intervals. Solves the issue of 3110 office hours starting at 4:40. Adds support for .env to store prostgres credentials to prevent any further passwords from being accidentally being pushed.
* change office hour increment intervals from 30 to 10 minutes in ProfessorOHInfo
* add dotenv package to scan for a .env file containing postgres login credentials in the server/ directory
* WILL break for those running the server locally. Will require you to create an .env file in server/ to store & protect local postgres db login credentials.
* Probably should also add support for manually typing in hours, with time validation sometime in the future.
> 3110 hours fix

- client/src/components/App.tsx
- client/src/components/includes/TopBar.tsx
Before this fix, the log out button doesn't quite work. This diff fixes this problem and makes the login and permission check login in App.tsx much cleaner.
Instead of mixing the code for isLogged in status check and professor view permission check, the new version keeps the concerns separate.
The old code has the bad behavior that an unlogged in user will be stuck in the loading state forever if he's trying to access professor view. This diff now corrects the behavior by directing the unauthenticated user to the login screen.
Try click logout. Things should just work.
> Fix App.tsx logic related to authentication

- client/src/components/includes/CalendarHeader.tsx
- client/src/components/includes/ProfessorOHInfo.tsx
- client/src/firebase.ts
Added support for creating and editing a session/series, to various levels.
- Creation/Editing support for a standalone session is fully ready.
- Creation/Editing support for series and series-related session is halfway there.
The reason for the half-way done series support is follows:
- The old backend generates sessions based on the series. i.e. series is used as template.
- To make it worse, the logic is different between creating and editing series.
Relevant code of old backend on master is linked below:
https://github.com/cornell-dti/office-hours/blob/ae7e5063d4ee6b466e420644ab24b14d548ce500/server/database/mock_database.sql#L567-L610
https://github.com/cornell-dti/office-hours/blob/ae7e5063d4ee6b466e420644ab24b14d548ce500/server/database/mock_database.sql#L776-L816
(Those blocks are …
> Support creating and editing sessions in ProfessorOHInfo

- client/src/components/includes/CalendarSessions.tsx
- client/src/components/includes/ProfessorCalendarRow.tsx
- client/src/components/includes/ProfessorOHInfo.tsx
- client/src/components/types/fireData.d.ts
Already made the change in database. This diff fixes the problem on the client side.
Context: references are bad for security rules and they should eventually be purged from the codebase.
> Using string id for session and session series

- client/src/components/App.tsx
- client/src/components/includes/ProfessorRolesTable.tsx
- client/src/components/pages/ProfessorView.tsx
- client/src/components/types/fireData.d.ts
- client/src/firehooks.ts
Part of the initiative to convert everything to string id.
> Make course users take string id for related documents

- client/src/components/includes/CalendarSessions.tsx
- client/src/firehooks.ts
Added a hook that can distinguish between loading state and empty result state.
Transformed the existing `useQuery` hook to simply call it.
> Introduce `useQueryWithLoading` for calendar sessions

- client/src/components/includes/CalendarDaySelect.tsx
- client/src/components/includes/CalendarSessions.tsx
- client/src/components/includes/CalendarView.tsx
On the client side, we still fetch all the sessions, but we filter it by date to feed into CalendarSessions component.
Since we are only fetching data for one course, and we don't pull the entire giant list, there won't be big performance hit.
On the bright side, it makes implementation significantly easier!
> Filter sessions by date

- client/src/components/includes/ProfessorCalendarRow.tsx
- client/src/firehooks.ts
Use the better `useQuery` hooks to replace the existing hacky solution.
*
- [] My changes requires a change to the documentation.
> Fix React hooks linter warning in professsor calendar view

- client/src/components/includes/ProfessorCalendarRow.tsx
- client/src/components/includes/ProfessorOHInfo.tsx
Previous this feature is broken due to an incorrect initial value and broken query.
Now both are fixed.
> Unbreak manage TA functionality for session management

- client/src/components/includes/ProfessorRolesTable.tsx
- client/src/components/pages/ProfessorView.tsx
- client/src/components/types/fireData.d.ts
- client/src/firebasefunctions.ts
Firebase security rules do not let you do query; instead, you can only get document by id or check exists. Our current setup requires to perform a query in `courseUsers` collection to check whether current auth user is a professor of a certain class, which is unachievable with firebase security rule.
The only solution is to duplicate the data in `courses` collection. Since number of professors and tas should be small, it should not create a huge performance overhead. It even introduces a benefit: now with the duplicated data, the query in `ProfessorRolesTable` can be implemented more efficiently.
> Store professor and ta list in `FireCourse`

- client/src/components/includes/CalendarHeader.tsx
- client/src/constants.ts
- client/src/firehooks.ts
A few diffs ago, I setup the singleton observable infra. The idea is that the query is only performed once, and make other resources that depend on this data subscribe to a single source of truth.
This diff finishes up the performance optimization inside `firehook.ts`. It caches all the fetches courses, and only do filter based on already fetched data.
> More efficient firebase hooks by reusing existing data

- client/src/components/includes/SessionView.tsx
- client/src/components/pages/SplitView.tsx
With this approach, we will be able to compute ahead and finished stat on the client side, at least for the focused session.
* Query questions in `SplitView`
* Use `componentDidUpdate` instead of a listener of `componentDidMount` in `SessionView`
> Lift questions to split view

- client/src/components/includes/CourseCard.tsx
- client/src/components/includes/CourseSelection.tsx
- client/src/components/includes/TopBar.tsx
- client/src/components/pages/CourseEditView.tsx
- client/src/components/pages/CourseSelectionView.tsx
- client/src/firehooks.ts
This diff completely implemnents the backend support for student self-enroll model.
Frontend will automatically compute a list of classes to enroll and unenroll based on user's selected list and a list of all classes. It can correctly handle the case that professor/TAs cannot unenroll themselves from the interface.
With the firebase reimplementation, saving can happen instantaneously. Do we still need a save and cancel button? @ngwattcos @vanessaw1 @connielei @abcdefguan 
Some designs have not been implemented yet. For example:
- distinguish between current and past courses
- home page design
> Completely implement student enrollment model

- client/src/components/includes/SessionQuestion.tsx
- client/src/components/includes/SessionQuestionsContainer.tsx
- client/src/components/includes/SessionView.tsx
- client/src/firehooks.ts
This diff is built upon the foundation of the previous two hookification diffs.
With prefetch, we can reduce the number of IO from O(n) to O(1), and remove a lot of unnecessary caching logic in SessionQuestion component!
> Pre-fetch tags for questions in SessionView

- client/src/components/App.tsx
- client/src/components/includes/CalendarView.tsx
- client/src/components/includes/CourseSelection.tsx
- client/src/components/includes/ProfessorRolesTable.tsx
- client/src/components/includes/SessionView.tsx
- client/src/components/pages/CourseEditView.tsx
- client/src/components/pages/CourseSelectionView.tsx
- client/src/components/pages/SplitView.tsx
- client/src/components/types/fireData.d.ts
- client/src/firebasefunctions.ts
- client/src/firehooks.ts
To improve performance of the questions container, this diff is a must: we should be able to prefetch a list of all course users along with user information in one request. Thus, `users` and `courseUsers` collection must be merged.
The implementation is constrained by several facts:
- Enforcibility of security rules
- Efficiency of query
Due to some weird constraint of firebase security rules, it's not possible to store the role and course enrollment together. Therefore, I have to split it to `courses` and `roles` field. If we store the `student` field, it's impossible to enforce the rule that only professsor can edit role. Therefore, I made the role == `student` implicit. I documented all the invaraints in `fireData.d.ts`.
> Merge users and courseUsers collection

- client/src/components/includes/ProfessorRolesTable.tsx
- client/src/components/includes/SessionQuestion.tsx
- client/src/components/includes/SessionQuestionsContainer.tsx
- client/src/components/includes/SessionView.tsx
- client/src/firehooks.ts
With the help of last diff, we are finally able to prefetch users information to avoid O(n) IO for client side join! Now our most IO intensive page achieves optimal IO efficiency!
> Optimize questions information loading

- client/src/utilities/singleton-observable-hook.ts
Put `singletonObservable` into useEffect dependency to fix caching issue
> Unbreak `createUseParamaterizedSingletonObservableHook`

- .gitignore
- client/.editorconfig
- client/src/components/includes/AddQuestion.tsx
- client/src/components/includes/CalendarSessionCard.tsx
- client/src/components/includes/SessionInformationHeader.tsx
- client/src/components/includes/SessionQuestion.tsx
- client/src/components/pages/SplitView.tsx
- client/src/components/types/fireData.d.ts
- client/src/utilities/questions.ts
The value is calculated incorrectly because it uses the field `resolved`, which turned out to be unreliable. Instead, we should delete this field, and derive whether the question has been resolved from the field `status`.
> Unbreak ahead count computation

- client/src/components/includes/SessionQuestion.tsx
- client/src/components/types/fireData.d.ts
During office hour today, Scott mentions that we might want a virtual whiteboard.
Implementing one is hard, but provide link to one is easy: we add an optional field to question called `taComment`. TA can edit this field, and it will be presented to the students. We can implement notification for this in this way in the future:
```typescript
useEffect(() => {
if (cachedOldComment !== newComment && isStudent) {
fireNotification(...);
}
}, [cachedOldComment, newComment, isStudent]);
```
Right now the GUI does not look good, so it's gates behind a flag. You must enable it by manually running `localStorage.setItem('FEATURE_TA_COMMENT_ENABLE_FLAG', 'true')` in your console.
Student:
TA:
This should not be merged until we got PM and designer approval.
> Let TA add comments to student question

- client/src/components/types/fireData.d.ts
- client/src/firebasefunctions.ts
These values are never needed. The old backend uses it essentially as variables
> Eliminate session series in DB

- src/components/App.tsx
Right now, our routing logic in `App.tsx` is a complete mess. The condition check for login status, data loading status, permissions, and course redirect logic are merged together in a giant block. Sometimes, the order of those checks matters and sometimes it doesn't. It's not immediatelty clear from this giant mess what's the correct flow of check. What's worse, it's also hard to reason about whether the current logic is correct. (hint: it's not)
This diff aims to clean up the giant mess by breaking it down into layers of composible react hooks. Each layer checks one thing only. The routing flow is therefore easier to understand: you unwrap the hooks layer by layer to see what's necessary to check in each step.
This change allows us to add a default route to the end of the routing switch …
> Routing logic improvements

- .eslintrc.json
- src/components/includes/CourseSelection.tsx
- src/components/includes/ProfessorOHInfo.tsx
- src/components/includes/SessionView.tsx
- src/components/pages/SplitView.tsx
- src/firebasefunctions.ts
Suddently GitHub actions sets the `CI=true` envvar, which causes the build to fail because it has linter warnings. ([link](https://github.com/cornell-dti/office-hours/runs/556229940)) This diff unbreaks master build by commenting out code that contains unused variables to unbreak the CI.
Now we have zero linter warnings! Check CI logs
> Unbreak master CI run

- src/components/includes/SessionView.tsx
- src/components/pages/ProfessorPeopleView.tsx
- src/firehooks.ts
Previously, we use on a client-side join between users and questions regardless whether the join is necessary. (The join in unnecessary for students since user information is never displayed to them.) This diff avoids such join for students.
Note on security rules:
It's not correct to simply ban all users table read by students. Following exceptions have to be added:
- user can read their own stuff
- professor, ta, admin can read everything
- student can read professors and ta's info (for displaying TA profile picture)
Use a student account. Try log `users` after the line (see diff)
```ts
const users = useCourseUsersMap(course.courseId, isTa);
```
You will find the map is always empty.
> [security] Avoid blanket users table read

- src/styles/login/LoginView.less
Fix #300 by explicitly calculating left offset
> Fix contactText centering css bug on Safari

- src/styles/calendar/CalendarHeader.less
Fix #294.
Chrome:
Firefox:
Safari:
> Fix arrow-down incorrect rotation css

- package.json
Mode the env-var set code close to `yarn build`, so it's actually applied during build.
Build it locally by `yarn deploy:staging`. Serve it. Log out. Log in. You will see the login url is qmi-test, which is the staging url
> Fix staging build config

- src/components/includes/SessionQuestion.tsx
- src/components/includes/SessionQuestionsContainer.tsx
The latest privacy fix splits questions and questionSlots. This left over a bug that students cannot see their own questions now. This diff fetches the full question when the question belongs to the student.
It also fixes a bug where tags are not shown.
Join as student, post your question, now you can see your content.
> Unbreak student view for their own questions

- src/components/types/fireData.d.ts
- src/firebasefunctions.ts
`createdAt` and `lastActivityAt` are never used. We should avoid storing unused information.
Everything still compiles, which proves that these two fields are unused.
> [privacy] Store less user information

- src/components/includes/CourseCard.tsx
- src/components/includes/CourseSelection.tsx
- src/styles/courses/CourseCard.less
Fixes #324, and makes each course cards the same width
Tested on desktop (Firefox, Chrome)
> Enrollment Model Minor Fixes

- src/components/includes/SessionView.tsx
- src/firebasefunctions.ts
- src/firehooks.ts
1) there are > 10 TAs in a course. Attempting to view the AdminView causes an error because loading TAs/profs uses ```useCourseProfessorMap``` and ```useCourseTAMap```, which break when they attempt to query > 10 TAs or > 10 professors in a course at once
2) a professor attempts to add ≥ 10 TAs at once in ProfessorRolesTable.
3) loading SessionView in a class with > 10 TAs. (Or > 10 professors. Which is unlikely).
Break up a single batched queries that involve 'in' into chunks of size 10, the maximum size limit that Firebase's 'in' query supports.
Replaces calls to ```useQueryWithLoading``` in some cases. The only difference with ```useQueryWithLoading``` is that it takes in a function that generates multiple queries (these are the result of breaking up our intended query into multiple …
> Fix borken Firebase 'in' query with more

- src/components/includes/AddQuestion.tsx
- src/components/includes/Analytics.tsx
- src/components/includes/CalendarDateItem.tsx
- src/components/includes/CalendarDaySelect.tsx
- src/components/includes/CalendarSessions.tsx
- src/components/includes/CalendarView.tsx
- src/components/includes/CalendarWeekSelect.tsx
- src/components/includes/Popup.tsx
- src/components/includes/ProfessorSettings.tsx
- src/components/includes/ProfessorSidebar.tsx
- src/components/includes/ProfessorTagInfo.tsx
- src/components/includes/ProfessorTagsDelete.tsx
- src/components/includes/QuestionsBarChart.tsx
- src/components/includes/SessionQuestionsContainer.tsx
- src/components/includes/SessionView.tsx
- src/components/includes/registerServiceWorker.ts
- src/styles/calendar/CalendarDaySelect.scss
Fix some easy linter errors.
Some of the a11y fixes are tricky, since I have to restyle something. It appears to me that the original authors are just abusing the default style provided by span, div, without considering that we need to use `button` to convey the semantic meaning of button to make the website accessible.
Less linter errors in CI. Changed styles are identical to the old ones.
> Fix linter errors

- src/components/includes/ProfessorOHInfo.tsx
Fixes  #337
* Tested with creating a new session
* Tested with updating an existing session and saving changes
- The issue was calling clearFields when saving changes to an existing session so that it cleared the pre-populated fields. clearFields should only be called when creating new sessions to clear out inputs.
- The TA selection dropdown does not completely clear out when using clearFields, which may be an issue with the dropdown component itself?
None
> Clear OH info only for new sessions

- types/react-web-notification/index.d.ts
This typedef is unnecessary since `react-web-notification` is already written in TS. 
CI passes, which shows that this file is really redundant.
> Remove unnecessary type definition

- src/components/includes/SessionQuestionsContainer.tsx
- src/components/includes/SessionView.tsx
- src/firehooks.ts
The silent onError callback led to unreliable updates of question documents and thus virtual location issues.
From my debugging, we'd sometimes silently fail the onSnapshot call and/or load an un-updated version of the document and per the docs after onError is called onUpdate will never be called again.
Thus, letting the error silently fail proved to be a dangerous foot gun.
I've added a hook which queries for all questions within a given session that the user asked. We then filter this locally. This shouldn't be much more costly than a single document snapshot and it should avoid any potential race conditions.
Test locally and in the development environment.
None
> Fix race condition with onSnapshot.

- public/static/js/main.9cebe396.js
Our old instance of queueme.in didn't set its cache headers correctly so for some people index.html is permanently cached. To fix this, we're going to insert a script which will forcibly remove the service worker and reload the instance.
The script is harmless, unless you have an old install.
Contact a team mate with a broken instance and ask them to reload the page.
This should be removed in a few weeks.
None
> Add static script to force migration.

- src/components/includes/ProfessorTagInfo.tsx
Both the name of the assignment _and_ the active state should be updated if they change.
- Create a new assignment
- Click the edit button
- Change the active/inactive toggle
- Click save
- Ensure the change survives a refresh
This was a result of an incomplete implementation when switching to Firestore
None
> Fix editing assignment 'active' state.

- src/components/includes/SessionQuestion.tsx
Fixed issue #400 by wrapping the dot menu in a div. 
Tested this on professor, TA, and student view, and the dot menu no longer appears stretched.
None
> Wrapped dot menu in a div to fix stretching problem

- src/styles/login/LoginButton.scss
I fixed the bug on Chrome where the Google logo on the QMI landing page extended past the sign in button.
I just had QMI running locally and checked the the Google logo was properly formatted in both Chrome and Firefox.
N/A
N/A
None
> fixed logo height and removed border

- functions/src/index.ts
- src/components/types/fireData.d.ts
This PR adds the second part of the ability to assign roles to users who do not exist in the database yet, which vastly simplifies the process of onboarding TAs and other professors for a course.
This PR adds the firebase function onUserCreate, which - upon the creation of a new Queue Me In user - checks the `pendingUsers` collection for a pending user with a matching email. If a `pendingUser` is found, the roles of the pendingUser document are copied over to the newly-created user, and each of the classes specified in the new roles will gain the newly-created user as that specified role. In addition, now that the user has been created, roles can be added to that user normally, so the user's entry in pendingUsers is deleted.
1. Create a new fake gmail account.
2. Add a new document in the …
> Support adding roles to pending users.

- src/constants.ts
Changes semester start to yesterday (Jan. 17) to allow interested folks to start using Queue Me In early.
> fast-forward semester start

- package.json
- src/firebasefunctions.ts
- src/utilities/date.ts
- yarn.lock
Renames function `datePlus` to `datePlusWithOffset(date: Date, offsetInSecs: number)`. This function now considers the UTC offsets of `date` and `date + offsetInSecs` and adds the difference (expressed in minutes and multiplied by 60 to get seconds) to the initially calculated offset.
Introduces helper method `utcOffsetOfDate(date, offset = 0)` to calculate the UTC offset in minutes.
In `createSeries`, replaces `const currentDate` with `let` and calculates the next date with `currentDate = datePlusWithDST(currentDate, 7 * 24 * 3600 * 1000)`, which adjusts the next date with respect to daylight savings time.
**NOTE**
I'm not entirely sure if `getWeekOffsets` / `normalizeDateToWeekStart` / `normalizeDateToDateStart` correctly handle daylight savings time. Since they are raw offsets I'm …
> Attempt to fix timezones in createSeries.

- src/components/includes/AddQuestion.tsx
Addresses issue #490. The link that students provide when joining the queue for a hybrid office hours session now gets displayed to TAs.  
Join a hybrid office hours session queue as a student. Sign in as a TA, and the link that you provided when joining the queue should be now visible.
None
> Display student link to TAs in hybrid office hours

- src/components/includes/TopBar.tsx
- src/styles/TopBar.scss
Logo Updated
Updated the import statement within the TopBar.tsx file, and then changed the width styling within TopBar.scss because the aspect ratio of the previous navbar logo was 2:1 whereas this logo is 1:1. It is worth noting that this logo is thus slightly taller than the previous (~4px taller) and takes slightly more vertical space. This appears to have very little affect on the spacing of the other elements in the navbar, however.
Changed window size, both width and height, and observed that expected behavior occurred with resizing (and TopBar disappearing at certain width). Navigated throughout the website to make sure there is no unexpected behavior with the logo.
> Updated import for logo in TopBar and fixed styles for new aspect ratio

- src/components/includes/AddQuestion.tsx
There were a few missing transitions in the add question state machine that were causing the following (and similar) bug: 
- select a primary tag 
- select a secondary tag 
- reselect a primary tag (which will clear the secondary tag)
- you can still proceed to enter a location and question and the join button seems clickable
The state machine is outlined [here](https://github.com/cornell-dti/office-hours/wiki/AddQuestion-Component#state-machine-outline) 
When you unselect a primary tag, secondary tag, clear location, or question, the join the queue card goes back to the step that you changed (everything else gets cleared)
None
> Add missing transitions in add question state machine 

- src/components/pages/CourseEditView.tsx
- src/components/pages/CourseSelectionView.tsx
- src/firehooks.ts
Added a new observable hook for a pendingUser document associated with the current user, so that when a user first logs in, it verifies whether the cloud function will run.
If the user has no associated pendingUser document, the course selection view loads as normal. If the user has an associated pendingUser document, the <Loading /> sematic ui React component notifies the user that there is logic running such that they cannot access the page. 
Tested loading with a new user both with and without a pendingUser document associated.  Also verified that the other course selection (non-editing view) is unaffected. 
Possible future development may involve a new component for this specific case that is less ambiguous. The loading screen currently is just the loading circle, while perhaps a …
> Added loading for new users during cloud function latency

- src/components/includes/AdminCourseCard.tsx
- src/components/includes/AdminCourseCreator.tsx
- src/components/includes/AdminEditableCourseCard.tsx
- src/components/includes/AdminReadOnlyCourseCard.tsx
- src/components/includes/ProfessorRolesTable.tsx
- src/components/includes/TopBar.tsx
- src/components/pages/AdminView.tsx
- src/styles/AdminView.scss
- src/styles/professor/ProfessorRoles.scss
I utilized the Material UI package to refactor the grid system for the courses and make it more responsive, styled some of the buttons, made the courses into Material UI Cards, refactored out the multiple components in the AdminView file, and added the TopBar to the admin page.
- Replaced the current grid style system with Grid components from @material-ui, which also makes the grid responsive--four courses per row on a very large screen, three per large, two per small, one per extra small. This fixes #497.
- Refactored the code within AdminView, which contained four functional components internally. These have been separated into /includes/[AdminCourseCard, AdminCourseCreator, AdminEditableCourseCard, AdminReadOnlyCourseCard].
- Updates some styles for the AdminView page, such as turning …
> Fixing issue #497, refactoring AdminView into multiple components, and adding some styles to AdminView

- src/components/includes/SessionView.tsx
- src/components/pages/SplitView.tsx
- src/firebasefunctions/sessionQuestion.ts
Moved the logic in SessionView that is responsible for updating the virtual location of a question after a TA assigns themself to that question to the sessionQuestion file. 
Moved the logic in SplitView that is responsible for removing a student's question from the queue to the sessionQuestion file. 
Ask a question then remove it, the question should be marked as retracted in the database (verify by looking at data in firestore) 
As a TA, assign a student's question to yourself. The student should be able to navigate to your virtual location when they click on join. 
None
> Refactor backend logic from SplitView and SessionView

- src/components/pages/AdminView.tsx
- src/components/pages/BlogCMS.tsx
- src/components/types/fireData.d.ts
- src/firebasefunctions/blogPost.ts
- src/firehooks.ts
Adding admins collection to database, adapting security rules to use the admins collection, and blocking access to /admin and /blog in the front end.
- Verify that with admin privileges (which consists of your email being in the admins collection) allow you to access secure resources and the /admin and /blog routes.
- Verify that removing yourself from the admins collection prevents access to secured resources and redirects you from the /admin and /blog routes when you attempt to access them.
None
> Restricting front end access to /admin and /blog

- src/components/pages/SplitView.tsx
Fixes issue #526. The notification reference error was caused because there is no variable named `Notification` (this variable is stored in window) so it must be referenced using `window?.Notification`
Connect ios device to macbook with a cable. Run `ifconfig` in terminal to find the ip address that you need to run localhost on ios device. Open `http://<ip address>:3000 `. Sign in** and select an office hour session. The app should redirect you to that session (and should not crash). 
** You need to authorize the domain that you're using to sign into the app using firebase. To do this, go [here](https://console.firebase.google.com/u/1/project/qmi-test/authentication/providers) and add the ip address to authorized domains.
None
> Fix notification reference error for ios devices

- src/components/includes/CSVUploadView.tsx
Change email inputs to lowercase to avoid issues when adding new professors/tas. Previously, if the ta/professor email was all uppercase, a new pending user would be created  in firestore with an all uppercase email. 
Add a new professor/ta with an uppercase email. A new pending user should not be created with an all uppercase email in firestore.
None
> Change all professor/ta email inputs to lowercase

- src/components/includes/AdminCourseCreator.tsx
Fixed bug where term and year values were switched and cleaned up the form itself. Also changed semester from input field to just text, since semester (FA21) is simply the term(FA) + year(21) (it didn't make sense to have the admin re-enter this info). Also added form input validation.
Created several sample courses and ensured they worked/validated properly.
In the future the form itself should be made prettier.
None
> Admin course creation bugfix

- src/components/includes/CSVUploadView.tsx
- src/firebasefunctions/importProfessorsOrTAs.ts
Fixed a CSV upload bug where uploading a CSV that updated the roles of users would not entirely work.
I noticed that if you updated the roles of users in both the professor and TA roles, the updates would not be correctly reflected in the admin page---the courses collection would not have the correct list of TAs and professors.
- Have a CSV file that updates the role of some users as TAs and some users as Professors (MAKE SURE you have both), and proceed with import
- Make sure the admin page and the Firestore database shows the correct user placement in both the users collection in the roles field as well as in the courses collection in the tas and professors fields.
None
> Fixed CSV bug

- src/components/includes/CalendarSessions.tsx
- src/components/includes/TopBarNotifications.tsx
- src/styles/calendar/CalendarSessions.scss
Makes past office hours automatically collapsed (unless there are no current office hours) and allows expanding as well. Also makes the time for notifications in 12 hour, not 24 hour. 
- Have a course with at least one past office hour and at least one current office hour. On clicking the course (or refresh), the past office hours should be automatically collapsed but able to be expanded.
- Have a course with only past office hours. They should be automatically expanded on clicking on the course (or refreshing), but still able to be collapsed
- check that a notif past noon has 12 hour time, with am/pm correct.
None
> Adding collapsing past office hours, fixing 24 hour time on notifications

- src/components/includes/LoginModal.tsx
- src/firebasefunctions/user.ts
For users that we have manually made a login for (email/password), Google authentication does not supply a name or photoUrl, which results in us constantly updating the database to "Dummy name" and "Dummy photo". I rectified this by making the database transaction only run in the case that we have a defined value for name and photo.
Log in normally with your netID and test that your name/phone number/photoUrl are maintained correctly. Log in with a username/password combo (The "having trouble logging in" button at the very bottom right of the home page", can use user:alex@alex.com, pass:alex@alex.com to verify) and check that name/phone number/photoUrl are maintained correctly.
None
> Fixing default values autofilling on every login for manually constructed users

- src/components/includes/CommentsContainer.tsx
1. Updates order of chat messages to be by ascending time rather than descending time
2. Moves reply/new comment to bottom of list of comments/chat messages
Before:
After:
Tested by adding, viewing, and deleting chat messages during office hours in both Student and Professor/TA view. 
None
> Fix chat messages order

- src/components/includes/CalendarDateItem.tsx
- src/components/includes/CalendarDaySelect.tsx
- src/components/includes/CalendarView.tsx
- src/media/sessionIndicator.svg
- src/styles/blogPosts/Notifications.scss
- src/styles/calendar/CalendarDaySelect.scss
Adds gray dot below all days with office hours on calendar. Dot under day becomes invisible if that day is clicked, dot becomes visible again if a different day is clicked.
Made test office hours and tested clicking through days of the calendar.
None
> Add office hours calendar dots

- src/components/includes/TopBar.tsx
- src/components/includes/TopBarNotifications.tsx
Fixed bug where the notifications menu would be hidden behind profile menu if profile menu was open before the notifications icon was clicked. Now, the menus switch if the different buttons are clicked in any order. Passed the showMenu variable and the function to change it down to the TopBarNotifications component.
Tested by running the website and clicking the notifications icon and the profile icon in different ways multiple times.
- [ x ] I have updated the documentation accordingly.
> Fixed Notifications Menu Bug

- src/components/includes/CourseSelection.tsx
- src/firebasefunctions/session.ts
- src/styles/courses/CourseSelection.scss
This PR adds functionality to collapse and expand former courses on the classes page. When the page is initially loaded, the former courses default to collapsed. 
None
> Collapse former classes

- src/components/includes/ProfessorOHInfoDelete.tsx
Previously we were not able to delete an OH session/series if it had passed. I removed the logic for checking if an OH has passed so that all OH sessions would be deletable.
Before: 
After:
None
> Bug fix: Enabled deleting OH

- src/components/includes/AdminReadOnlyCourseCard.tsx
- src/styles/AdminView.scss
- added icons to collapse professor and TA lists
- editing and roles button now change color when the cursor hovers over them
- icons should appear when there is at least one person in the TA/Professor list, otherwise only "None" should be displayed
- Hover mouse over editing and roles button to see if they change
- Check that icons default to being collapsed
- Check that clicking icons toggles between collapsed and expanded list
- Change users to be different roles and see if the icons appear accordingly
> Collapsible TA/Professor view

- package.json
- yarn.lock
This PR updates yarn and misc dependencies that enables us to upgrade node version from 14.17.3 to 16.20.2.
Run:
nvm install 16.20.2
nvm use 16.20.2
nvm alias default 16.13.0  
yarn install
yarn start
None
> upgraded node to v16.13.0

- functions/package.json
- functions/yarn.lock
- package.json
- yarn.lock
Upgrade firebase-tools to v11.18.0 to fix a deployment error saying `Error: Failed to fetch Run service undefined`
This newer version of firebaes-tools should improve support for deploying firebase functions and fix this issue
None
> Upgrade firebase-tools to 11.18.0

- package.json
fix build staging openssl provider not found
None
> Fix master build issues

- src/components/includes/ProfessorOHInfo.tsx
- src/firebasefunctions/series.ts
Fixed a bug where Zoom links for weekly recurring virtual office hours wouldn't save properly, resulting in a blank link field when the screen was reloaded.
Example of the link not saving after reloading on prod.
https://github.com/user-attachments/assets/08ec10b6-8a94-4ef6-af83-72d0bfdd544d
As seen below, the link is still there after reloading.
https://github.com/user-attachments/assets/862acd71-ec6f-4de4-9779-0f74eb264385
None
> Fix Virtual Recurring OH TALink not saving

- src/components/includes/ProfessorOHInfo.tsx
- Fixed bug that prevented CS 2110 Course Staff from editing start time for a hybrid weekly recurring office hours
- Description of bug:
- Essentially, in each of CS 2110's session documents in Firestore, the TALink field was missing
- When TALink is pulled from the CS 2110 session document, it is undefined
- This undefined TALink is passed into updateSession (which calls firestore.collection().doc().update()) when one tries to edit OH time
- This returns an error because updating a document with a field with a value of undefined is unsupported by Firebase
- Fix:
- When TALink is undefined, made the default value of TALink an empty string ("")
- This prevents TALink from being undefined, which allows updateSession / firestore.collection().doc().update() to be called without errors
- Check …
> Fix Bug That Prevented Editing OH Time

- src/components/includes/ProfessorTagInfo.tsx
- src/styles/professor/ProfessorTagInfo.scss
- fixed add new tag input field at the top, under "Tags" and above the persisted list of new tags
- added extra margin so that text field and selected child tags don't get squeezed together
Screenshot of the resulting fixes:
Previously:
> Minor Tag Info UI Fixes

- src/components/includes/SessionView.tsx
- only read from the documents in the questions collection that match this session: `firestore.collection("questions").where("sessionId", "==", session.sessionId)`
- remove excess useEffect dependencies so unsubscribe is only called a handful of times, instead of tens of times
Originally, onSnapshot gets called a butt ton of times:
https://github.com/user-attachments/assets/0b00e146-fa06-4b5f-89e5-667cc00231d8
Now, it's only called a handful of times (resizing not shown here, but it doesn't get called on resizing now):
https://github.com/user-attachments/assets/1efc8c61-94ba-4b79-804e-605f32b2bf20
Tested that questions feedback form still shows up immediately after a question gets answered and submits properly. Ensured onSnapshot is limited to a few calls instead of racking up tens of …
> Efficient Questions Monitoring

- src/components/includes/Wrapped.tsx
- src/media/wrapped/arrow.svg
- src/media/wrapped/plus.svg
- src/media/wrapped/plus2.svg
- src/styles/Wrapped.scss
- src/styles/WrappedAnimation.scss
Building on [this Wrapped Frontend PR](https://github.com/cornell-dti/office-hours/pull/854) and this [animation PR](https://github.com/cornell-dti/office-hours/pull/869), creates a loading animation screen that transitions into the welcome screen.
https://github.com/user-attachments/assets/bf624ea5-5de3-4869-b902-a3ef7349edf4
- Made animation faster
- Fixed some centering issues on different devices
- Loading animation should look centered on different device widths
- No lags or delays, and dots and arrows should only show up after the welcome component is rendered
- I made the loading animation have a 0.8s delay because shortening this caused some odd CSS flickering, and this was the lowest time I could go without the flickering
None
> Loading Screen to Welcome Screen

- src/styles/WrappedAnimation.scss
Fixed unexpected jerks for red circle in loading animation.
Before (on main branch):
https://github.com/user-attachments/assets/64f99330-1f3f-4735-925a-464f359386a9
After: 
https://github.com/user-attachments/assets/7d07fbd6-9f2a-47f4-ab34-379a33407d1b
- Unsure why this lag didn't show up on my original branch, but I think removing the extra rotations made the calculations simpler and less laggy
None
> Fix Lagging intro animation

- src/components/includes/CourseSelection.tsx
- src/components/pages/SplitView.tsx
Remove the useEffects that render Wrapped on entry
QMI Wrapped doesn't keep appearing on reload anymore.
> Hide Wrapped Until Clicked

- src/components/includes/Wrapped.tsx
NumberPeople originally used only totalMinutes as digits, but this resulted in inaccurate numbers being reflected in TaStudentsHelped. A number parameter was added to NumberPeople so that the correct number could be inputted. 
Changed Firebase values for numStudentsHelped and totalMinutes to be different. 
None
> Add parameter to NumberPeople

- src/components/includes/TopBarNotifications.tsx
- src/components/includes/Wrapped.tsx
- src/styles/Wrapped.scss
Since the launch of QMI Wrapped, there were some minor UI bugs that needs to be addressed:
1) Align the blue top text in the wrapped slides to be consistent with the white texts
2) Ensure consistency in font size and font weight across the slides
3) Pin the wrapped notification at the top of the notification banner
Most of the changes in this PR are CSS changes made in `Wrapped.scss`
Tested via local server
**Keep Wrapped Notification on top of the notif banner**
**Fix font size and weight consistency**
https://github.com/user-attachments/assets/f92a2a3c-475d-495e-b7e6-79dace52e379
None
> Fixed UI Bugs for QMI Wrapped 

- src/components/pages/SplitView.tsx
- src/constants.ts
Set current semester to SP25 with start date 1/15 and end date 5/18. Also changed wrapped start/end date to remove visibility on home page
- Wrapped not visible
- Only sp 25 classes available to select
None
> Update constants.ts for SP2025

- .gitignore
- src/components/includes/CalendarSessionCard.tsx
- src/styles/MessageModal.scss
- src/styles/calendar/CalendarDaySelect.scss
- src/styles/calendar/CalendarSessions.scss
Small css fixes for #862 , especially mobile view
- changed dot indicator to actually be red dot, not flash green when TA active
- removed long fadeIn time for mobile modal view
- adjust "export to gcal/ical" text font size for mobile view
- added hover effect to selecting calendar dates to match design prototypes
https://github.com/user-attachments/assets/56443c82-a067-446f-8e65-d456a1d77e5a
- red dot only appears for TAs, not students, instead of previously styled indicator when there is a question in the queue
- could test with more than one question if it still works
None
> Calendar export redesign css fixes

- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/yarn.lock
- src/components/includes/SessionView.tsx
- src/components/types/fireData.d.ts
- yarn.lock
*UPDATE 2:*
Refactored the firebase cloud function `onQuestionStatusUpdate`. Instead of maintaining a `resolvedQuestionArray` field inside of the session documents and having to update the session everytime after calling `removeQuestionDisplayFeedback` to remove the processed questions, maintain a `recentlyResolvedQuestion` field inside of specific user document.
The previous logic of updating session document would require modifying firebase security rules because we wouldn't want non-admin users to update office hour sessions without restrictions, so only Professors or TA should have update/write permission. Thus, the approach of updating the user document after the questions are resolved and processed does not require changing any of the existing firebase security rules. Doing so also …
> Eric / Implement Firebase Function to Monitor Question Status Change

- functions/src/index.ts
- src/components/types/fireData.d.ts
While implementing the function for this <a href="https://www.notion.so/1740ad723ce1817bb989e7d8329019ea?v=1740ad723ce181809fa7000c727ccc7e&p=1b90ad723ce180fea0eff8412b4004b9&pm=s"> ticket </a>, I realized a bug where although a prof/TA resolved a question, there was no question feedback prompts shown on the student side. I checked the firebase function loggers as shown below:
The user document was not successfully updated due to the invalid field `recentlyResolvedQuestion.resolvedAt`. This field is not necessary for the functionality of monitoring questions, and was intended to be used for debugging. This PR provides remedy for this issue by simply removing `resolvedAt` entirely. 
The updated version of the cloud function `onQuestionStatusUpdate` is already deployed to the test QMI …
> Eric/Fixed Bug where Question Feedback Prompt is not displayed

- firebase.json
- src/components/pages/AdminView.tsx
Trying to fix this error once deployed:
From this stackOverflow answer: https://stackoverflow.com/questions/65132937/firebaseerror-the-datastore-operation-timed-out
it is likely bc we are calling hooks for useAll--- which gets the *entire* collection which is probably too many reads.
We can see the reads have spiked in the graph too:
None
> deployment analytics fix
